.

diff --git a/bin/_ b/bin/_
--- a/bin/_
+++ b/bin/_
@@ -17,36 +17,32 @@
 .prelude
 
 .say() {
-	local msg
+	echo -e "${@-""}"
+}
 
-	if [[ $# -gt 0 ]]; then
-		for msg; do
-			echo -e >&2 "${msg_prefix_:-}${msg}"
-		done
-	else
-		echo >&2 ""
+.out() {
+	local arg
+
+	for arg; do
+		echo -e >&2 "$arg"
+	done
+
+	if .piped; then
+		cat >&2
 	fi
 }
 
 .cry() {
-	local msg
-
 	if [[ $# -gt 0 ]]; then
-		for msg; do
-			echo -e >&2 "${msg_prefix_:-W: }${msg}"
-		done
+		echo -e >&2 "W: $*"
 	else
 		echo >&2 ""
 	fi
 }
 
 .die() {
-	local msg
-
 	if [[ $# -gt 0 ]]; then
-		for msg; do
-			echo -e >&2 "${msg_prefix_:-E: }${msg}"
-		done
+		echo -e >&2 "E: $*"
 	else
 		echo >&2 ""
 	fi
@@ -55,12 +51,8 @@
 }
 
 .bug() {
-	local msg
-
 	if [[ $# -gt 0 ]]; then
-		for msg; do
-			echo -e >&2 "${msg_prefix_:-B: }${msg}"
-		done
+		echo -e >&2 "BUG: $*"
 	else
 		echo >&2 ""
 	fi
@@ -69,15 +61,7 @@
 }
 
 .bye() {
-	local msg
-
-	if [[ $# -gt 0 ]]; then
-		for msg; do
-			echo -e >&2 "${msg_prefix_:-}${msg}"
-		done
-	else
-		echo >&2 ""
-	fi
+	.out "$@"
 
 	exit 0
 }
@@ -121,11 +105,11 @@
 }
 
 .piped() {
-	[[ -t 0 ]]
+	[[ ! -t 0 ]]
 }
 
 .interactive() {
-	[[ -t 1 ]]
+	[[   -t 1 ]]
 }
 
 .bool() {
@@ -339,9 +323,9 @@ flag._post_() {
 	fi
 
 	if   [[ -n ${lo:-} ]] && [[ $n -lt $lo ]]; then
-		.die- 'Too few arguments' # FIXME
+		.die 'Too few arguments' # FIXME
 	elif [[ -n ${hi:-} ]] && [[ $n -gt $hi ]]; then
-		.die- 'Too many arguments'
+		.die 'Too many arguments'
 	else
 		return 0
 	fi
@@ -349,118 +333,166 @@ flag._post_() {
 	flag.usage_ 1
 }
 
+# color.sh - Colors
+
+# shellcheck disable=2034
+color._init() {
+	declare -Ag _color=(
+		# Basic colors with variants - prefix +: bold, prefix -: dim, suffix -: reverse
+
+		[black]='\e[38;5;8m'          [+black]='\e[1m\e[38;5;8m'     [-black]='\e[38;5;0m'
+		[black-]='\e[48;5;8m'         [+black-]='\e[1m\e[48;5;8m'    [-black-]='\e[48;5;0m'
+
+		[blue]='\e[38;5;12m'          [+blue]='\e[1m\e[38;5;12m'     [-blue]='\e[38;5;4m'
+		[blue-]='\e[48;5;12m'         [+blue-]='\e[1m\e[48;5;12m'    [-blue-]='\e[48;5;4m'
+
+		[cyan]='\e[38;5;14m'          [+cyan]='\e[1m\e[38;5;14m'     [-cyan]='\e[38;5;6m'
+		[cyan-]='\e[48;5;14m'         [+cyan-]='\e[1m\e[48;5;14m'    [-cyan-]='\e[48;5;6m'
+
+		[green]='\e[38;5;10m'         [+green]='\e[1m\e[38;5;10m'    [-green]='\e[38;5;2m'
+		[green-]='\e[48;5;10m'        [+green-]='\e[1m\e[48;5;10m'   [-green-]='\e[48;5;2m'
+
+		[magenta]='\e[38;5;13m'       [+magenta]='\e[1m\e[38;5;13m'  [-magenta]='\e[38;5;5m'
+		[magenta-]='\e[48;5;13m'      [+magenta-]='\e[1m\e[48;5;13m' [-magenta-]='\e[48;5;5m'
+
+		[red]='\e[38;5;9m'            [+red]='\e[1m\e[38;5;9m'       [-red]='\e[38;5;1m'
+		[red-]='\e[48;5;9m'           [+red-]='\e[1m\e[48;5;9m'      [-red-]='\e[48;5;1m'
+
+		[white]='\e[38;5;15m'         [+white]='\e[1m\e[38;5;15m'    [-white]='\e[38;5;7m'
+		[white-]='\e[48;5;15m'        [+white-]='\e[1m\e[48;5;15m'   [-white-]='\e[48;5;7m'
+
+		[yellow]='\e[38;5;11m'        [+yellow]='\e[1m\e[38;5;11m'   [-yellow]='\e[38;5;3m'
+		[yellow-]='\e[48;5;11m'       [+yellow-]='\e[1m\e[48;5;11m'  [-yellow-]='\e[48;5;3m'
+
+		# Attributes
+
+		[bold]='\e[1m'                [dark]='\e[2m'                 [underlined]='\e[4m'
+		[blink]='\e[5m'               [reverse]='\e[7m'              [reset]='\e[0m'
+
+		# Priority aliases
+		[high]='\e[1m'                [medium]=''                    [low]='\e[2m'
+	)
+}
+
+color.expand() {
+	while [[ $# -gt 0 ]]; do
+		local -n color_expand_=${1?missing argument}
+		shift
+
+		local key value
+		for key in "${!color_expand_[@]}"; do
+			value=${color_expand_[$key]}
+
+			color_expand_[$key]=${_color[$value]}
+		done
+	done
+}
+
+color.setup() {
+	while [[ $# -gt 0 ]]; do
+		local key=${1%%=*}; value=${1#*=}
+
+		if [[ -n ${_color[$value]:-} ]]; then
+			_color[$key]=${_color[$value]}
+		else
+			_color[$key]=$value
+		fi
+
+		shift
+	done
+}
+
+color.code() {
+	local code="${_color[${1?missing argument}]:-}"
+
+	[[ -n $code ]] || .bug "No such color: $1"
+
+	echo -en "$code"
+}
+
+color._init
+
 # ui.sh - UI functions
 
-shopt -s expand_aliases
+# shellcheck disable=2034,2154
+ui._init() {
+	declare -Ag _sign _sign_color _text_color
 
+	# Style
+
+	_sign[panic]='✖';      _sign_color[panic]=red;          _text_color[panic]=high
+	_sign[caution]='★';    _sign_color[caution]=+cyan;      _text_color[caution]=high
+	_sign[error]='✗';      _sign_color[error]=+red;         _text_color[error]=high
+	_sign[headline]='>';   _sign_color[headline]=+cyan;     _text_color[headline]=high
+	_sign[info]='ℹ';       _sign_color[info]=-yellow;       _text_color[info]=low
+	_sign[plain]=' ';      _sign_color[plain]=+white;       _text_color[plain]=medium
+	_sign[question]='?';   _sign_color[question]=+yellow;   _text_color[question]=high
+	_sign[success]='✓';    _sign_color[success]=+green;     _text_color[success]=high
+	_sign[warning]='!';    _sign_color[warning]=+yellow;    _text_color[warning]=medium
+
+	color.expand _sign_color _text_color
+}
+
+# shellcheck disable=2034,2154
+ui._out() {
+	local name=${FUNCNAME[1]#*.}
+
+	local sign=${_sign[$name]}
+
+	local sign_color=${_sign_color[$name]} text_color=${_text_color[$name]} reset=${_color[reset]}
+
+	echo -e "${sign_color}${sign}${reset} ${text_color}$*${reset}"
+}
+
+ui.panic()    { ui._out "$@"; }
+ui.caution()  { ui._out "$@"; }
+ui.error()    { ui._out "$@"; }
+ui.headline() { ui._out "$@"; }
+ui.info()     { ui._out "$@"; }
+ui.plain()    { ui._out "$@"; }
+ui.question() { ui._out "$@"; }
+ui.success()  { ui._out "$@"; }
+ui.warning()  { ui._out "$@"; }
+
+# Report bug and exit failure
+ui.bug() {
+	ui.panic "$@" >&2; exit 127
+}
 
 # Print messages on standard error
 ui.say() {
-	local -A _=(
-		[.help]='[MESSAGE...]'
-		[.argc]=0-
-	)
-
-	flag.parse
-
-	ui._plain "$@"
+	ui.plain "$@" >&2
 }
 
-# Print error messages and exit failure
-ui.die() {
-	local -A _=(
-		[-unexit]=false
-		[.help]='[-unexit=BOOL [MESSAGE...]]'
-		[.argc]=0-
-	)
-
-	flag.parse
-
-	ui._error "$@"
-
-	flag.true unexit || exit 1
+# Print messages on standard error and exit success
+ui.bye() {
+	ui.plain "$@" >&2; exit 0
 }
 
 # Print warning messages on standard error
 ui.cry() {
-	local -A _=(
-		[.help]='[MESSAGE...]'
-		[.argc]=0-
-	)
-
-	flag.parse
-
-	ui._warning "$@"
+	ui.warning "$@" >&2
 }
 
-# Report bug and exit failure
-ui.bug() {
-	local -A _=(
-		[-unexit]=false
-		[.help]='[-unexit=BOOL [MESSAGE...]]'
-		[.argc]=0-
-	)
-
-	flag.parse
-
-	ui._bug "$@"
-
-	flag.true unexit || exit 127
+# Print error messages and exit failure
+ui.die() {
+	ui.error "$@" >&2; exit 1
 }
 
 # Print messages taking attention
 ui.hey() {
-	local -A _=(
-		[.help]='[MESSAGE...]'
-		[.argc]=0-
-	)
-
-	flag.parse
-
-	ui._hey "$@"
+	ui.headline "$@" >&2
 }
 
-# ui - Private functions
+ui._init
 
-ui._plain() {
-	local message
+shopt -s expand_aliases
 
-	for message; do
-		echo -e >&2 "$message"
-	done
-}
-
-ui._error() {
-	local message
-
-	for message; do
-		echo -e >&2 "E: $message"
-	done
-}
-
-ui._warning() {
-	local message
-
-	for message; do
-		echo -e >&2 "W: $message"
-	done
-}
-
-ui._bug() {
-	local message
-
-	for message; do
-		echo -e >&2 "B: $message"
-	done
-}
-
-ui._hey() {
-	local message
-
-	for message; do
-		echo -e >&2 "\\e[38;5;14m-->\\e[0m\\e[1m $message\\e[0m"
-	done
-}
+alias .bug=ui.bug
+alias .bye=ui.bye
+alias .cry=ui.cry
+alias .die=ui.die
+alias .hey=ui.hey
 
 # must.sh - Guard functions
 
@@ -590,6 +622,7 @@ must.interactive() {
 
 # self.sh - Functions related to program itself
 
+# Print self
 self() {
 	local path
 
@@ -854,7 +887,7 @@ declare -ag _at_exit_funcs_=()
 declare -ag _at_exit_files_=()
 
 # shellcheck disable=2120
-trap.setup() {
+trap._init() {
 	local -a signals=(EXIT HUP INT QUIT TERM)
 
 	[[ $# -eq 0 ]] || signals=("$@")
@@ -904,6 +937,8 @@ _at_exit_cleanup_() {
 
 	rm -rf -- "${_at_exit_files_[@]}"
 }
+
+trap._init
 
 # temp.sh - Functions involving temporary directories or files
 
@@ -2408,10 +2443,11 @@ zip._prep_untar_() {
 
 if [[ ${UNDERSCORE_SOURCE:-} = true ]] || [[ "${BASH_SOURCE[0]}" = "$0" ]]; then
 	declare -Ag _help=(
-		['ui.say']='Print messages on standard error'
-		['ui.die']='Print error messages and exit failure'
-		['ui.cry']='Print warning messages on standard error'
 		['ui.bug']='Report bug and exit failure'
+		['ui.say']='Print messages on standard error'
+		['ui.bye']='Print messages on standard error and exit success'
+		['ui.cry']='Print warning messages on standard error'
+		['ui.die']='Print error messages and exit failure'
 		['ui.hey']='Print messages taking attention'
 		['must.e']='Test -e'
 		['must.f']='Test -f'
@@ -2430,6 +2466,7 @@ if [[ ${UNDERSCORE_SOURCE:-} = true ]] || [[ "${BASH_SOURCE[0]}" = "$0" ]]; then
 		['must.callable']='Function must exist'
 		['must.piped']='Stdin must exist'
 		['must.interactive']='Stdout must exist'
+		['self']='Print self'
 		['self.version']='Print self version'
 		['self.name']='Print self name'
 		['self.path']='Print self path'
@@ -2437,7 +2474,6 @@ if [[ ${UNDERSCORE_SOURCE:-} = true ]] || [[ "${BASH_SOURCE[0]}" = "$0" ]]; then
 		['array.join']='Join array with the given separator'
 		['array.dup']='Duplicate array'
 		['array.contains']='Array contains the given element'
-		['trap.setup']='shellcheck disable=2120'
 		['trap']='Prevent using trap'
 		['at_exit']='Register hooks at exit'
 		['at_exit_files']='Register files/directories to clean up at exit'
@@ -2514,21 +2550,15 @@ if [[ ${UNDERSCORE_SOURCE:-} = true ]] || [[ "${BASH_SOURCE[0]}" = "$0" ]]; then
 	.usage() {
 		local cmd
 
-		# shellcheck disable=2128
-		.say "$PROGNAME COMMAND... [-FLAG=VALUE...] [ARGS]"
-		.say "Commands:"
-
-		# shellcheck disable=2154
+		# shellcheck disable=2154,2128
 		for cmd in "${!_command[@]}"; do
 			local fun=${_command[$cmd]}
 
 			printf "\\t%-24s  %s\n" "$cmd" "${_help[$fun]}"
-		done | sort >&2
+		done | sort | .out "$PROGNAME COMMAND... [-FLAG=VALUE...] [ARGS]" "Commands:"
 	}
 
 	.execute() {
-		trap.setup
-
 		if [[ $# -eq 0 ]]; then
 			.usage
 			.die 'Command required'
@@ -2599,7 +2629,7 @@ EOF
 		sed 's/^\t\t//' <<'EOF'
 		declare -grx UNDERSCORE=$UNDERSCORE
 
-		.() {
+		._() {
 			case ${1:-} in
 			-root)
 				[[ ${EUID:-} -eq 0 ]] || { echo >&2 'Root privileges required.'; exit 1; }
@@ -2648,7 +2678,7 @@ EOF
 		}
 
 		# shellcheck disable=1090
-		. "$@"
+		._ "$@"
 EOF
 	}
 
diff --git a/bin/t b/bin/t
--- a/bin/t
+++ b/bin/t
@@ -17,36 +17,32 @@
 .prelude
 
 .say() {
-	local msg
+	echo -e "${@-""}"
+}
 
-	if [[ $# -gt 0 ]]; then
-		for msg; do
-			echo -e >&2 "${msg_prefix_:-}${msg}"
-		done
-	else
-		echo >&2 ""
+.out() {
+	local arg
+
+	for arg; do
+		echo -e >&2 "$arg"
+	done
+
+	if .piped; then
+		cat >&2
 	fi
 }
 
 .cry() {
-	local msg
-
 	if [[ $# -gt 0 ]]; then
-		for msg; do
-			echo -e >&2 "${msg_prefix_:-W: }${msg}"
-		done
+		echo -e >&2 "W: $*"
 	else
 		echo >&2 ""
 	fi
 }
 
 .die() {
-	local msg
-
 	if [[ $# -gt 0 ]]; then
-		for msg; do
-			echo -e >&2 "${msg_prefix_:-E: }${msg}"
-		done
+		echo -e >&2 "E: $*"
 	else
 		echo >&2 ""
 	fi
@@ -55,12 +51,8 @@
 }
 
 .bug() {
-	local msg
-
 	if [[ $# -gt 0 ]]; then
-		for msg; do
-			echo -e >&2 "${msg_prefix_:-B: }${msg}"
-		done
+		echo -e >&2 "BUG: $*"
 	else
 		echo >&2 ""
 	fi
@@ -69,15 +61,7 @@
 }
 
 .bye() {
-	local msg
-
-	if [[ $# -gt 0 ]]; then
-		for msg; do
-			echo -e >&2 "${msg_prefix_:-}${msg}"
-		done
-	else
-		echo >&2 ""
-	fi
+	.out "$@"
 
 	exit 0
 }
@@ -121,11 +105,11 @@
 }
 
 .piped() {
-	[[ -t 0 ]]
+	[[ ! -t 0 ]]
 }
 
 .interactive() {
-	[[ -t 1 ]]
+	[[   -t 1 ]]
 }
 
 .bool() {
@@ -339,15 +323,176 @@ flag._post_() {
 	fi
 
 	if   [[ -n ${lo:-} ]] && [[ $n -lt $lo ]]; then
-		.die- 'Too few arguments' # FIXME
+		.die 'Too few arguments' # FIXME
 	elif [[ -n ${hi:-} ]] && [[ $n -gt $hi ]]; then
-		.die- 'Too many arguments'
+		.die 'Too many arguments'
 	else
 		return 0
 	fi
 
 	flag.usage_ 1
 }
+
+# color.sh - Colors
+
+# shellcheck disable=2034
+color._init() {
+	declare -Ag _color=(
+		# Basic colors with variants - prefix +: bold, prefix -: dim, suffix -: reverse
+
+		[black]='\e[38;5;8m'          [+black]='\e[1m\e[38;5;8m'     [-black]='\e[38;5;0m'
+		[black-]='\e[48;5;8m'         [+black-]='\e[1m\e[48;5;8m'    [-black-]='\e[48;5;0m'
+
+		[blue]='\e[38;5;12m'          [+blue]='\e[1m\e[38;5;12m'     [-blue]='\e[38;5;4m'
+		[blue-]='\e[48;5;12m'         [+blue-]='\e[1m\e[48;5;12m'    [-blue-]='\e[48;5;4m'
+
+		[cyan]='\e[38;5;14m'          [+cyan]='\e[1m\e[38;5;14m'     [-cyan]='\e[38;5;6m'
+		[cyan-]='\e[48;5;14m'         [+cyan-]='\e[1m\e[48;5;14m'    [-cyan-]='\e[48;5;6m'
+
+		[green]='\e[38;5;10m'         [+green]='\e[1m\e[38;5;10m'    [-green]='\e[38;5;2m'
+		[green-]='\e[48;5;10m'        [+green-]='\e[1m\e[48;5;10m'   [-green-]='\e[48;5;2m'
+
+		[magenta]='\e[38;5;13m'       [+magenta]='\e[1m\e[38;5;13m'  [-magenta]='\e[38;5;5m'
+		[magenta-]='\e[48;5;13m'      [+magenta-]='\e[1m\e[48;5;13m' [-magenta-]='\e[48;5;5m'
+
+		[red]='\e[38;5;9m'            [+red]='\e[1m\e[38;5;9m'       [-red]='\e[38;5;1m'
+		[red-]='\e[48;5;9m'           [+red-]='\e[1m\e[48;5;9m'      [-red-]='\e[48;5;1m'
+
+		[white]='\e[38;5;15m'         [+white]='\e[1m\e[38;5;15m'    [-white]='\e[38;5;7m'
+		[white-]='\e[48;5;15m'        [+white-]='\e[1m\e[48;5;15m'   [-white-]='\e[48;5;7m'
+
+		[yellow]='\e[38;5;11m'        [+yellow]='\e[1m\e[38;5;11m'   [-yellow]='\e[38;5;3m'
+		[yellow-]='\e[48;5;11m'       [+yellow-]='\e[1m\e[48;5;11m'  [-yellow-]='\e[48;5;3m'
+
+		# Attributes
+
+		[bold]='\e[1m'                [dark]='\e[2m'                 [underlined]='\e[4m'
+		[blink]='\e[5m'               [reverse]='\e[7m'              [reset]='\e[0m'
+
+		# Priority aliases
+		[high]='\e[1m'                [medium]=''                    [low]='\e[2m'
+	)
+}
+
+color.expand() {
+	while [[ $# -gt 0 ]]; do
+		local -n color_expand_=${1?missing argument}
+		shift
+
+		local key value
+		for key in "${!color_expand_[@]}"; do
+			value=${color_expand_[$key]}
+
+			color_expand_[$key]=${_color[$value]}
+		done
+	done
+}
+
+color.setup() {
+	while [[ $# -gt 0 ]]; do
+		local key=${1%%=*}; value=${1#*=}
+
+		if [[ -n ${_color[$value]:-} ]]; then
+			_color[$key]=${_color[$value]}
+		else
+			_color[$key]=$value
+		fi
+
+		shift
+	done
+}
+
+color.code() {
+	local code="${_color[${1?missing argument}]:-}"
+
+	[[ -n $code ]] || .bug "No such color: $1"
+
+	echo -en "$code"
+}
+
+color._init
+
+# ui.sh - UI functions
+
+# shellcheck disable=2034,2154
+ui._init() {
+	declare -Ag _sign _sign_color _text_color
+
+	# Style
+
+	_sign[panic]='✖';      _sign_color[panic]=red;          _text_color[panic]=high
+	_sign[caution]='★';    _sign_color[caution]=+cyan;      _text_color[caution]=high
+	_sign[error]='✗';      _sign_color[error]=+red;         _text_color[error]=high
+	_sign[headline]='>';   _sign_color[headline]=+cyan;     _text_color[headline]=high
+	_sign[info]='ℹ';       _sign_color[info]=-yellow;       _text_color[info]=low
+	_sign[plain]=' ';      _sign_color[plain]=+white;       _text_color[plain]=medium
+	_sign[question]='?';   _sign_color[question]=+yellow;   _text_color[question]=high
+	_sign[success]='✓';    _sign_color[success]=+green;     _text_color[success]=high
+	_sign[warning]='!';    _sign_color[warning]=+yellow;    _text_color[warning]=medium
+
+	color.expand _sign_color _text_color
+}
+
+# shellcheck disable=2034,2154
+ui._out() {
+	local name=${FUNCNAME[1]#*.}
+
+	local sign=${_sign[$name]}
+
+	local sign_color=${_sign_color[$name]} text_color=${_text_color[$name]} reset=${_color[reset]}
+
+	echo -e "${sign_color}${sign}${reset} ${text_color}$*${reset}"
+}
+
+ui.panic()    { ui._out "$@"; }
+ui.caution()  { ui._out "$@"; }
+ui.error()    { ui._out "$@"; }
+ui.headline() { ui._out "$@"; }
+ui.info()     { ui._out "$@"; }
+ui.plain()    { ui._out "$@"; }
+ui.question() { ui._out "$@"; }
+ui.success()  { ui._out "$@"; }
+ui.warning()  { ui._out "$@"; }
+
+# Report bug and exit failure
+ui.bug() {
+	ui.panic "$@" >&2; exit 127
+}
+
+# Print messages on standard error
+ui.say() {
+	ui.plain "$@" >&2
+}
+
+# Print messages on standard error and exit success
+ui.bye() {
+	ui.plain "$@" >&2; exit 0
+}
+
+# Print warning messages on standard error
+ui.cry() {
+	ui.warning "$@" >&2
+}
+
+# Print error messages and exit failure
+ui.die() {
+	ui.error "$@" >&2; exit 1
+}
+
+# Print messages taking attention
+ui.hey() {
+	ui.headline "$@" >&2
+}
+
+ui._init
+
+shopt -s expand_aliases
+
+alias .bug=ui.bug
+alias .bye=ui.bye
+alias .cry=ui.cry
+alias .die=ui.die
+alias .hey=ui.hey
 
 # must.sh - Guard functions
 
@@ -477,6 +622,7 @@ must.interactive() {
 
 # self.sh - Functions related to program itself
 
+# Print self
 self() {
 	local path
 
@@ -538,6 +684,12 @@ self.install() {
 
 if [[ ${OVERSCORE_SOURCE:-} = true ]] || [[ "${BASH_SOURCE[0]}" = "$0" ]]; then
 	declare -Ag _help=(
+		['ui.bug']='Report bug and exit failure'
+		['ui.say']='Print messages on standard error'
+		['ui.bye']='Print messages on standard error and exit success'
+		['ui.cry']='Print warning messages on standard error'
+		['ui.die']='Print error messages and exit failure'
+		['ui.hey']='Print messages taking attention'
 		['must.e']='Test -e'
 		['must.f']='Test -f'
 		['must.d']='Test -d'
@@ -555,6 +707,7 @@ if [[ ${OVERSCORE_SOURCE:-} = true ]] || [[ "${BASH_SOURCE[0]}" = "$0" ]]; then
 		['must.callable']='Function must exist'
 		['must.piped']='Stdin must exist'
 		['must.interactive']='Stdout must exist'
+		['self']='Print self'
 		['self.version']='Print self version'
 		['self.name']='Print self name'
 		['self.path']='Print self path'
@@ -643,36 +796,20 @@ if [[ ${OVERSCORE_SOURCE:-} = true ]] || [[ "${BASH_SOURCE[0]}" = "$0" ]]; then
 		}
 
 		.say() {
-			local msg
-
-			if [[ $# -gt 0 ]]; then
-				for msg; do
-					echo -e >&2 "${msg_prefix_:-}${msg}"
-				done
-			else
-				echo >&2 ""
-			fi
+			echo -e "${@-""}"
 		}
 
 		.cry() {
-			local msg
-
 			if [[ $# -gt 0 ]]; then
-				for msg; do
-					echo -e >&2 "${msg_prefix_:-W: }${msg}"
-				done
+				echo -e >&2 "W: $*"
 			else
 				echo >&2 ""
 			fi
 		}
 
 		.die() {
-			local msg
-
 			if [[ $# -gt 0 ]]; then
-				for msg; do
-					echo -e >&2 "${msg_prefix_:-E: }${msg}"
-				done
+				echo -e >&2 "E: $*"
 			else
 				echo >&2 ""
 			fi
@@ -681,12 +818,8 @@ if [[ ${OVERSCORE_SOURCE:-} = true ]] || [[ "${BASH_SOURCE[0]}" = "$0" ]]; then
 		}
 
 		.bug() {
-			local msg
-
 			if [[ $# -gt 0 ]]; then
-				for msg; do
-					echo -e >&2 "${msg_prefix_:-B: }${msg}"
-				done
+				echo -e >&2 "BUG: $*"
 			else
 				echo >&2 ""
 			fi
@@ -776,7 +909,7 @@ EOF
 			local -A seen
 
 			local t
-			for t in $(declare -F | grep 'declare -f test[:]' | awk '{ print $3 }'); do
+			for t in $(declare -F | grep 'declare -f test[:_]' | awk '{ print $3 }'); do
 				if [[ -z ${seen[$t]:-} ]]; then
 					unset __test_status
 
@@ -820,11 +953,11 @@ EOF
 				local name=$1
 				shift
 
-				local assert=assert."$name"
+				local test=test."$name"
 
-				[[ $(type -t "$assert" || true) == function ]]
+				[[ $(type -t "$test" || true) == function ]]
 
-				"$assert" "$@"
+				"$test" "$@"
 
 				return 0
 			fi
