.

diff --git a/bin/_ b/bin/_
--- a/bin/_
+++ b/bin/_
@@ -383,6 +383,58 @@ flag._validate_() {
 	flag._nils_
 }
 
+# util.sh - Various non essential utility functions
+
+# Check the expirations of given files
+util.expired() {
+	local -i expiry=${1?${FUNCNAME[0]}: missing argument}; shift
+
+	[[ $expiry -gt 0 ]] || return 1
+
+	local file
+	for file; do
+		if [[ -e $file ]] && [[ -z $(find "$file" -mmin +"$expiry" 2>/dev/null) ]]; then
+			return 1
+		fi
+	done
+
+	return 0
+}
+
+# Capture outputs to arrays and return exit code
+# shellcheck disable=2034
+util.capture() {
+	local out err ret
+
+	if [[ ${1?${FUNCNAME[0]}: missing argument} != '-' ]]; then
+		local -n util_capture_out_=$1
+
+		out=$(mktemp)
+	fi
+	shift
+
+	if [[ ${1?${FUNCNAME[0]}: missing argument} != '-' ]]; then
+		local -n util_capture_err_=$1
+
+		err=$(mktemp)
+	fi
+	shift
+
+	"$@" >"${out:-/dev/stdout}" 2>"${err:-/dev/stderr}" && ret=$? || ret=$?
+
+	if [[ -n ${out:-} ]]; then
+		mapfile -t util_capture_out_ <"$out" || true
+		rm -f -- "$out"
+	fi
+
+	if [[ -n ${err:-} ]]; then
+		mapfile -t util_capture_err_ <"$err" || true
+		rm -f -- "$err"
+	fi
+
+	return $ret
+}
+
 # color.sh - Colors
 
 # shellcheck disable=2034
@@ -649,7 +701,7 @@ must.z() {
 
 # Must be root
 must.root() {
-	[[ ${EUID:-} -eq 0 ]]
+	[[ ${EUID:-} -eq 0 ]] || .die 'Root permissions required; please use sudo.'
 }
 
 # Command must success
@@ -1224,7 +1276,7 @@ url.is() {
 
 	if [[ $feature = local ]]; then
 		[[ $url =~ ^(/|./|file://) ]]
-		return
+		return 0
 	fi
 
 	url.parse_ "$url"
@@ -1649,7 +1701,7 @@ git.update() {
 
 	flag.parse
 
-	if .expired "${_[-expiry]}" .git/FETCH_HEAD; then
+	if util.expired "${_[-expiry]}" .git/FETCH_HEAD; then
 		git.must.clean
 		git pull --quiet origin
 	fi
@@ -1763,7 +1815,7 @@ git.update_() {
 	git.switch "${_[.branch]:-}"
 
 	local -i expiry=${_[-expiry]:-3}
-	if .expired "$expiry" .git/FETCH_HEAD; then
+	if util.expired "$expiry" .git/FETCH_HEAD; then
 		git.must.clean
 
 		.say 'Updating repository...'
@@ -2018,12 +2070,15 @@ export DEBIAN_FRONTEND=noninteractive APT_KEY_DONT_WARN_ON_DANGEROUS_USAGE=DontW
 
 # Install Debian packages
 deb.install() {
+	must.root
+
 	# shellcheck disable=2192
 	local -A _=(
 		[-missings]=false
 		[-shiny]=false
 
 		[.help]='PACKAGE...'
+		[.argc]=1-
 	)
 
 	flag.parse
@@ -2035,14 +2090,14 @@ deb.install() {
 		--no-install-recommends
 	)
 
-	local -a packages urls non_urls
+	local -a packages=() urls=() non_urls=()
 
 	local arg
 	for arg; do
-		if is.url "$arg"; then
-			urls+=("$arg")
-		else
+		if url.is "$arg" local || [[ -z $(url.is "$arg" proto) ]]; then
 			non_urls+=("$arg")
+		else
+			urls+=("$arg")
 		fi
 	done
 
@@ -2124,7 +2179,7 @@ deb.update() {
 
 	flag.parse
 
-	.expired 60 /var/cache/apt/pkgcache.bin || apt-get update -y
+	util.expired 60 /var/cache/apt/pkgcache.bin || apt-get update -y
 }
 
 # Add Debian repository
@@ -2562,6 +2617,8 @@ zip._prep_untar_() {
 if [[ ${UNDERSCORE_SOURCE:-} = true ]] || [[ "${BASH_SOURCE[0]}" = "$0" ]]; then
 	declare -Ag _help=(
 		['.prelude']='shellcheck disable=2034,2128'
+		['util.expired']='Check the expirations of given files'
+		['util.capture']='Capture outputs to arrays and return exit code'
 		['ui.bug']='Report bug and exit failure'
 		['ui.say']='Print messages on standard error'
 		['ui.bye']='Print messages on standard error and exit success'
