.

diff --git a/bin/_ b/bin/_
--- a/bin/_
+++ b/bin/_
@@ -134,248 +134,6 @@
 	unset _load_old_
 }
 
-# _.sh - Required functions
-
-_.available() {
-	local -A _=(
-		[.help]='PROGRAM'
-		[.argc]=1
-	)
-
-	flag.parse
-
-	.available "$@"
-}
-
-_.must() {
-	local -A _=(
-		[.help]='MESSAGE ARGS...|-- ARGS...'
-		[.argc]=0-
-	)
-
-	flag.parse
-
-	.must "$@" # FIXME
-}
-
-_.should() {
-	local -A _=(
-		[.help]='MESSAGE ARGS...|-- ARGS...'
-		[.argc]=0-
-	)
-
-	flag.parse
-
-	.should "$@"
-}
-
-# Try to run any file or url
-_.run() {
-	local -A _=(
-		[.help]='FILE|URL'
-		[.argc]=1
-	)
-
-	flag.parse
-
-	local url=$1
-
-	if url.is "$url" web; then
-		bin.run "$url"
-	elif url.is "$url" src; then
-		src.run "$url"
-	else
-		.die "Unsupported URL type: $url"
-	fi
-}
-
-# Check the expirations of given files
-_.expired() {
-	local -A _=(
-		[-expiry]=3
-
-		[.help]='[-expiry=MINUTES] FILE...'
-		[.argc]=1-
-	)
-
-	flag.parse
-
-	.expired "${_[-expiry]}" "$@"
-}
-
-# _ - Protected functions
-
-.out() {
-	local arg
-
-	for arg; do
-		echo -e "$arg"
-	done
-
-	if .piped; then
-		cat
-	fi
-}
-
-.err() {
-	.out "$@" >&2
-}
-
-.ask() {
-	.bug 'Not implemented'
-}
-
-.calling() {
-	local message="${1?${FUNCNAME[0]}: missing argument}"; shift
-
-	.say "--> $message"
-
-	"$@"
-}
-
-.getting() {
-	local message="${1?${FUNCNAME[0]}: missing argument}"; shift
-
-	.say "... $message"
-
-	"$@"
-}
-
-.running() {
-	local message="${1?${FUNCNAME[0]}: missing argument}"; shift
-
-	.say "... $message"
-
-	"$@"
-}
-
-.ok() {
-	.say "OK    $*"
-}
-
-.notok() {
-	.say "NOTOK $*"
-}
-
-.dbg() {
-	[[ $# -gt 0 ]] || return 0
-
-	# shellcheck disable=2178,2155
-	local -n dbg_=$1
-
-	echo "${!dbg_}"
-
-	local key
-	for key in "${!dbg_[@]}"; do
-		printf '  %-16s  %s\n' "${key}" "${dbg_[$key]}"
-	done | sort
-
-	echo
-}
-
-.piped() {
-	[[ ! -t 0 ]]
-}
-
-.interactive() {
-	[[   -t 1 ]]
-}
-
-.bool() {
-	local value=${1:-}
-
-	value=${value,,}
-
-	case $value in
-	true|t|1|on|yes|y)
-		return 0
-		;;
-	false|f|0|off|no|n|"")
-		return 1
-		;;
-	*)
-		.bug "Invalid boolean: $value"
-	esac
-}
-
-# Check the expirations of given files
-.expired() {
-	local -i expiry=${1?${FUNCNAME[0]}: missing argument}; shift
-
-	[[ $expiry -gt 0 ]] || return 1
-
-	local file
-	for file; do
-		if [[ -e $file ]] && [[ -z $(find "$file" -mmin +"$expiry" 2>/dev/null) ]]; then
-			return 1
-		fi
-	done
-
-	return 0
-}
-
-# Capture outputs to arrays and return exit code
-# shellcheck disable=2034,2178
-.capture() {
-	local out err ret
-
-	if [[ ${1?${FUNCNAME[0]}: missing argument} != '-' ]]; then
-		local -n capture_out_=$1
-
-		out=$(mktemp)
-	fi
-	shift
-
-	if [[ ${1?${FUNCNAME[0]}: missing argument} != '-' ]]; then
-		local -n capture_err_=$1
-
-		err=$(mktemp)
-	fi
-	shift
-
-	"$@" >"${out:-/dev/stdout}" 2>"${err:-/dev/stderr}" && ret=$? || ret=$?
-
-	if [[ -n ${out:-} ]]; then
-		mapfile -t capture_out_ <"$out" || true
-		rm -f -- "$out"
-	fi
-
-	if [[ -n ${err:-} ]]; then
-		mapfile -t capture_err_ <"$err" || true
-		rm -f -- "$err"
-	fi
-
-	return $ret
-}
-
-# Initialize underscore system
-
-.init() {
-	# Default variable as a hash
-	declare -gA _=()
-
-	# shellcheck disable=2034
-
-	# Core environment
-	if [[ ${EUID:-} -eq 0 ]]; then
-		readonly _RUN=${UNDERSCORE_VOLATILE_PREFIX:-/run/_}
-		readonly _USR=${UNDERSCORE_PERSISTENT_PREFIX:-/usr/local}
-		readonly _ETC=${UNDERSCORE_CONFIG_PATH:-/etc/_:"$_USR"/etc/_:"$_RUN"/etc}
-	else
-		XDG_RUNTIME_DIR=${XDG_RUNTIME_DIR:-/run/user/"$EUID"}
-		XDG_CONFIG_HOME=${XDG_CONFIG_HOME:-"$HOME"/.config}
-		XDG_CACHE_HOME=${XDG_CACHE_HOME:-"$HOME"/.cache}
-
-		readonly _RUN=${UNDERSCORE_VOLATILE_PREFIX:-"$XDG_RUNTIME_DIR"/_}
-		readonly _USR=${UNDERSCORE_PERSISTENT_PREFIX:-"$HOME"/.local}
-		readonly _ETC=${UNDERSCORE_CONFIG_PATH:-/etc/_:/usr/local/etc/_:"$XDG_CONFIG_HOME"/_:"$_RUN"/etc}
-	fi
-
-	export PATH="$_RUN"/bin:"$PATH"
-
-	unset -f "${FUNCNAME[0]}"
-}
-
 # flag.sh - Flag handling
 
 shopt -s expand_aliases
@@ -402,7 +160,8 @@ flag.usage_and_die_() {
 	.die "$@"
 }
 
-flag.usage_and_die_() {
+# shellcheck disable=2120
+flag.usage_and_bye_() {
 	flag.usage_
 
 	.bye "$@"
@@ -425,7 +184,7 @@ flag.parse_() {
 			if [[ $key =~ ^-.+$ ]] && [[ ! -v _[$key] ]]; then
 				.die "Unrecognized flag: $key"
 			fi
-		elif [[ $1 == '--' ]]; then
+		elif [[ $1 == '--' ]] && [[ -z ${_[.dash]:-} ]]; then
 			shift
 			break
 		else
@@ -541,12 +300,255 @@ flag._args_() {
 		return 0
 	fi
 
-	flag.usage_and_die "$message"
+	flag.usage_and_die_ "$message"
 }
 
 flag._validate_() {
 	flag._args_ "$@"
 	flag._nils_
+}
+
+# _.sh - Required functions
+
+_.available() {
+	local -A _=(
+		[.help]='PROGRAM'
+		[.argc]=1
+	)
+
+	flag.parse
+
+	.available "$@"
+}
+
+# Check the expirations of given files
+_.expired() {
+	local -A _=(
+		[-expiry]=3
+
+		[.help]='[-expiry=MINUTES] FILE...'
+		[.argc]=1-
+	)
+
+	flag.parse
+
+	.expired "${_[-expiry]}" "$@"
+}
+
+_.must() {
+	local -A _=(
+		[.help]='MESSAGE ARGS...|-- ARGS...'
+		[.argc]=2-
+		[.dash]=true
+	)
+
+	flag.parse
+
+	.must "$@"
+}
+
+# Try to run any file or url
+_.run() {
+	local -A _=(
+		[.help]='FILE|URL'
+		[.argc]=1
+	)
+
+	flag.parse
+
+	local url=$1
+
+	if url.is "$url" web; then
+		bin.run "$url"
+	elif url.is "$url" src; then
+		src.run "$url"
+	else
+		.die "Unsupported URL type: $url"
+	fi
+}
+
+_.should() {
+	local -A _=(
+		[.help]='MESSAGE ARGS...|-- ARGS...'
+		[.argc]=2-
+		[.dash]=true
+	)
+
+	flag.parse
+
+	.should "$@"
+}
+
+# _ - Protected functions
+
+.ask() {
+	.bug 'Not implemented'
+}
+
+.bool() {
+	local value=${1:-}
+
+	value=${value,,}
+
+	case $value in
+	true|t|1|on|yes|y)
+		return 0
+		;;
+	false|f|0|off|no|n|"")
+		return 1
+		;;
+	*)
+		.bug "Invalid boolean: $value"
+	esac
+}
+
+# Capture outputs to arrays and return exit code
+# shellcheck disable=2034,2178
+.capture() {
+	local out err ret
+
+	if [[ ${1?${FUNCNAME[0]}: missing argument} != '-' ]]; then
+		local -n capture_out_=$1
+
+		out=$(mktemp)
+	fi
+	shift
+
+	if [[ ${1?${FUNCNAME[0]}: missing argument} != '-' ]]; then
+		local -n capture_err_=$1
+
+		err=$(mktemp)
+	fi
+	shift
+
+	"$@" >"${out:-/dev/stdout}" 2>"${err:-/dev/stderr}" && ret=$? || ret=$?
+
+	if [[ -n ${out:-} ]]; then
+		mapfile -t capture_out_ <"$out" || true
+		rm -f -- "$out"
+	fi
+
+	if [[ -n ${err:-} ]]; then
+		mapfile -t capture_err_ <"$err" || true
+		rm -f -- "$err"
+	fi
+
+	return $ret
+}
+.calling() {
+	local message="${1?${FUNCNAME[0]}: missing argument}"; shift
+
+	.say "--> $message"
+
+	"$@"
+}
+
+.dbg() {
+	[[ $# -gt 0 ]] || return 0
+
+	# shellcheck disable=2178,2155
+	local -n dbg_=$1
+
+	echo "${!dbg_}"
+
+	local key
+	for key in "${!dbg_[@]}"; do
+		printf '  %-16s  %s\n' "${key}" "${dbg_[$key]}"
+	done | sort
+
+	echo
+}
+
+.err() {
+	.out "$@" >&2
+}
+
+# Check the expirations of given files
+.expired() {
+	local -i expiry=${1?${FUNCNAME[0]}: missing argument}; shift
+
+	[[ $expiry -gt 0 ]] || return 1
+
+	local file
+	for file; do
+		if [[ -e $file ]] && [[ -z $(find "$file" -mmin +"$expiry" 2>/dev/null) ]]; then
+			return 1
+		fi
+	done
+
+	return 0
+}
+
+.getting() {
+	local message="${1?${FUNCNAME[0]}: missing argument}"; shift
+
+	.say "... $message"
+
+	"$@"
+}
+
+.interactive() {
+	[[   -t 1 ]]
+}
+
+.notok() {
+	.say "NOTOK $*"
+}
+
+.ok() {
+	.say "OK    $*"
+}
+
+.out() {
+	local arg
+
+	for arg; do
+		echo -e "$arg"
+	done
+
+	if .piped; then
+		cat
+	fi
+}
+
+.piped() {
+	[[ ! -t 0 ]]
+}
+
+.running() {
+	local message="${1?${FUNCNAME[0]}: missing argument}"; shift
+
+	.say "... $message"
+
+	"$@"
+}
+
+# Initialize underscore system
+
+.init() {
+	# Default variable as a hash
+	declare -gA _=()
+
+	# shellcheck disable=2034
+
+	# Core environment
+	if [[ ${EUID:-} -eq 0 ]]; then
+		readonly _RUN=${UNDERSCORE_VOLATILE_PREFIX:-/run/_}
+		readonly _USR=${UNDERSCORE_PERSISTENT_PREFIX:-/usr/local}
+		readonly _ETC=${UNDERSCORE_CONFIG_PATH:-/etc/_:"$_USR"/etc/_:"$_RUN"/etc}
+	else
+		XDG_RUNTIME_DIR=${XDG_RUNTIME_DIR:-/run/user/"$EUID"}
+		XDG_CONFIG_HOME=${XDG_CONFIG_HOME:-"$HOME"/.config}
+		XDG_CACHE_HOME=${XDG_CACHE_HOME:-"$HOME"/.cache}
+
+		readonly _RUN=${UNDERSCORE_VOLATILE_PREFIX:-"$XDG_RUNTIME_DIR"/_}
+		readonly _USR=${UNDERSCORE_PERSISTENT_PREFIX:-"$HOME"/.local}
+		readonly _ETC=${UNDERSCORE_CONFIG_PATH:-/etc/_:/usr/local/etc/_:"$XDG_CONFIG_HOME"/_:"$_RUN"/etc}
+	fi
+
+	export PATH="$_RUN"/bin:"$PATH"
+
+	unset -f "${FUNCNAME[0]}"
 }
 
 # color.sh - Colors
@@ -835,7 +837,11 @@ ui.echo() {
 
 	local sign_color=${_sign_color[$name]} text_color=${_text_color[$name]} reset=${_color[reset]}
 
-	echo -e "${sign_color}${sign}${reset} ${text_color}${message}${reset}"
+	if [[ -n ${sign:-} ]]; then
+		echo -e "${sign_color}${sign}${reset} ${text_color}${message}${reset}"
+	else
+		echo -e "${text_color}${message}${reset}"
+	fi
 }
 
 # self.sh - Functions related to program itself
@@ -3106,6 +3112,7 @@ EOF
 			.source
 		else
 			.init
+
 			app.dispatch "$@"
 		fi
 	}
