.

diff --git a/bin/_ b/bin/_
--- a/bin/_
+++ b/bin/_
@@ -245,6 +245,9 @@ shopt -s expand_aliases
 # shellcheck disable=2142
 alias flag.parse='flag.parse_ "$@"; local -a __a; flag.args_ __a; set -- "${__a[@]}"; unset -v __a'
 
+# shellcheck disable=2034
+declare -gr NIL="\0"
+
 flag.usage_() {
 	if [[ -n ${_[.help]:-} ]]; then
 		# shellcheck disable=2128
@@ -288,9 +291,9 @@ flag.parse_() {
 		shift
 	done
 
-	flag._post_ $argc
-
 	_.load flag_result_
+
+	flag._validate_ $argc
 }
 
 flag.args_() {
@@ -302,15 +305,32 @@ flag.env_() {
 }
 
 flag.true() {
-	.bool "${_[-$1]:-}"
+	.bool "${_[$1]:-}"
 }
 
 flag.false() {
 	! flag.true "$@"
 }
 
-flag._post_() {
-	local n=${1?missing argument}
+flag.nil() {
+	[[ ${_[$1]:-} = "$NIL" ]]
+}
+
+flag._nils_() {
+	local -a required=()
+
+	local key
+	for key in "${!_[@]}"; do
+		if flag.nil "$key"; then
+			required+=("$key")
+		fi
+	done
+
+	[[ ${#required[@]} -eq 0 ]] || .die "Missing values for: ${required[*]}"
+}
+
+flag._args_() {
+	local n=${1?${FUNCNAME[0]}: missing argument}; shift
 
 	local argc=${_[.argc]:-0}
 
@@ -335,6 +355,11 @@ flag._post_() {
 	fi
 
 	flag.usage_ 1
+}
+
+flag._validate_() {
+	flag._args_ "$@"
+	flag._nils_
 }
 
 # color.sh - Colors
@@ -1759,7 +1784,7 @@ src.run() {
 	src.install_ "$@"
 
 	src.run_ "${_[.dir]}"
-	flag.false test || src.test_ "${_[.dir]}"
+	flag.false -test || src.test_ "${_[.dir]}"
 }
 
 # src - Protected functions
@@ -1958,13 +1983,13 @@ deb.install() {
 		fi
 	done
 
-	if flag.true missings; then
+	if flag.true -missings; then
 		deb._missings packages "${non_urls[@]}"
 	else
 		packages=("${non_urls[@]}")
 	fi
 
-	if flag.true shiny; then
+	if flag.true -shiny; then
 		local target
 
 		if is.debian stable; then
@@ -2219,7 +2244,7 @@ filetype.mime() {
 
 	local file=$1; must.f "$file"
 
-	if flag.true zip; then
+	if flag.true -zip; then
 		file --mime-type --brief --uncompress-noreport "$file"
 	else
 		file --mime-type --brief "$file"
@@ -2263,7 +2288,7 @@ filetype.is._mime_() {
 	local expected=${1?${FUNCNAME[0]}: missing argument}; shift
 
 	local mime
-	if flag.true zip; then
+	if flag.true -zip; then
 		mime=$(file --mime-type --brief --uncompress-noreport "$file")
 	else
 		mime=$(file --mime-type --brief "$file")
@@ -2341,7 +2366,7 @@ zip.unpack() {
 
 	"$func" "$in" "$out"
 
-	if flag.true clean; then
+	if flag.true -clean; then
 		rm -f -- "$in"
 	fi
 }
@@ -2441,7 +2466,7 @@ zip._prep_unzip_() {
 	[[ -n $out ]] || out=${in%.*}
 
 	if [[ -e $out ]]; then
-		if flag.true force; then
+		if flag.true -force; then
 			must.success rm -rf -- "$out"
 		else
 			.die "File already exist: $out"
@@ -2460,7 +2485,7 @@ zip._prep_untar_() {
 	[[ -n $out ]] || out=${in%.tar.*}
 
 	if [[ -e $out ]]; then
-		if flag.true force; then
+		if flag.true -force; then
 			must.success rm -rf -- "$out"
 		else
 			.die "Directory already exist: $out"
@@ -2536,6 +2561,7 @@ if [[ ${UNDERSCORE_SOURCE:-} = true ]] || [[ "${BASH_SOURCE[0]}" = "$0" ]]; then
 		['filetype.mime']='What mime type'
 		['filetype.is']='Detect file type'
 		['zip.unpack']='Unpack compressed file'
+		['app.dispatch']='shellcheck disable=2154'
 	)
 
 	declare -Ag _command=(
@@ -2577,20 +2603,30 @@ if [[ ${UNDERSCORE_SOURCE:-} = true ]] || [[ "${BASH_SOURCE[0]}" = "$0" ]]; then
 		['url is']='url.is'
 	)
 
-	.usage() {
+	# app.sh - Application handling
+
+	app.usage() {
 		local cmd
 
-		# shellcheck disable=2154,2128
+		# shellcheck disable=2128
+		.say "$PROGNAME COMMAND... [-FLAG=VALUE...] [ARGS]"
+		.say "Commands:"
+
+		# shellcheck disable=2154
 		for cmd in "${!_command[@]}"; do
 			local fun=${_command[$cmd]}
 
 			printf "\\t%-24s  %s\n" "$cmd" "${_help[$fun]}"
-		done | sort | .err "$PROGNAME COMMAND... [-FLAG=VALUE...] [ARGS]" "Commands:"
+		done | sort >&2
 	}
 
-	.execute() {
+	# shellcheck disable=2154
+	app.dispatch() {
+		local orig="${*}"
+
 		if [[ $# -eq 0 ]]; then
-			.usage
+			cli.usage
+
 			.die 'Command required'
 		fi
 
@@ -2602,37 +2638,37 @@ if [[ ${UNDERSCORE_SOURCE:-} = true ]] || [[ "${BASH_SOURCE[0]}" = "$0" ]]; then
 			shift
 
 			if [[ $# -eq 0 ]]; then
-				.usage
+				cli.usage
+
 				.die 'Help topic required'
 			fi
 		fi
 
-		local -a args=("$@") found=() try
+		local -a args=("$@") try
 
+		local cmd
 		while [[ $# -gt 0 ]]; do
 			try+=("$1")
-
-			[[ -n ${_command[${try[*]}]:-} ]] || break
-
-			found+=("${try[*]}")
-
 			shift
+
+			if [[ -n ${_command[${try[*]}]:-} ]]; then
+				cmd=${try[*]}
+				args=("$@")
+			fi
 		done
 
-		[[ ${#found[@]} -gt 0 ]] || .die "No command found: ${args[*]}"
+		[[ -n ${cmd:-} ]] || .die "No command found: $orig"
 
-		local cmd=${found[-1]}
 		local fun=${_command["$cmd"]}
 
 		readonly PROGNAME+=("$cmd")
 
-		.init
-
 		if [[ -n ${help:-} ]]; then
 			.say "${_help[$fun]}" ""
+
 			"$fun" -help
 		else
-			"$fun" "$@"
+			"$fun" "${args[@]}"
 		fi
 	}
 
@@ -2718,7 +2754,7 @@ EOF
 		if ! .interactive && [[ $# -eq 0 ]]; then
 			.source
 		else
-			.execute "$@"
+			app.dispatch "$@"
 		fi
 	}
 
