.

diff --git a/bin/_ b/bin/_
--- a/bin/_
+++ b/bin/_
@@ -1077,7 +1077,7 @@ defer.init() {
 
 		local func
 		for func in "${_defer_funcs_[@]}"; do
-			"$func" || .cry "Deferred function failed: $func"
+			"$func" || [[ $SIG = INT ]] || [[ $SIG = QUIT ]] || .cry "Deferred function failed: $func"
 		done
 
 		if [[ -v _defer_clean_ ]] && [[ "${#_defer_clean_[@]}" -gt 0 ]]; then
@@ -1138,21 +1138,21 @@ temp.dir() {
 # Execute command in temp dir
 temp.inside() {
 	# shellcheck disable=2128
-	local temp_dir orig_dir=$PWD
-	temp.dir temp_dir
+	local temp_inside_ orig_dir_=$PWD
+	temp.dir temp_inside_
 
-	must.success cd "$temp_dir"
+	must.success cd "$temp_inside_"
 	"$@"
-	must.success cd "$orig_dir"
+	must.success cd "$orig_dir_"
 
-	rm -rf -- "$temp_dir"
+	rm -rf -- "$temp_inside_"
 }
 
 temp.clean() {
 	while [[ $# -gt 0 ]]; do
 		local -n temp_clean_=$1; shift
 
-		[[ -z ${!temp_clean_:-} ]] || rm -f -- "${!temp_clean_}"
+		rm -rf -- "$temp_clean_"
 	done
 }
 
@@ -1278,18 +1278,19 @@ url.is() {
 	url.is_ "$feature" "$value"
 }
 
-# Assert URL is getable (via supported protocols)
+# Transform URL to a getable (via supported providers) form
 url.getable() {
-	local -A _=(
-		[.help]='URL'
-		[.argc]=1
-	)
+	local -n url_getable_=${1?${FUNCNAME[0]}: missing argument}; shift
 
-	flag.parse
+	if [[ $url_getable_ =~ ^[^:]+:// ]]; then
+		return 0
+	elif [[ $url_getable_ =~ ^(github.com|gitlab.com|bitbucket.com) ]]; then
+		url_getable_="https://$url_getable_"
 
-	local url=$1
+		return 0
+	fi
 
-	[[ $url =~ ^(https|http|ssh|git|ftp):// ]]
+	return 1
 }
 
 # url - Protected functions
@@ -1395,7 +1396,7 @@ http.get() {
 
 	local url=$1
 
-	[[ $url =~ ^.*:// ]] || url=https://$url
+	[[ $url =~ ^[^:]+:// ]] || url=https://$url
 
 	curl -fsSL "$url"
 }
@@ -1431,9 +1432,10 @@ file.install() {
 		[-mode]=
 		[-owner]=
 		[-prefix]=
+		[-quiet]=
 
 		[.help]='[-(group|mode|owner|prefix)=VALUE] URL [FILE]'
-		[.argc]=1
+		[.argc]=1-
 	)
 
 	flag.parse
@@ -1466,7 +1468,7 @@ file.chogm() {
 		[-owner]=
 
 		[.help]='[-(group|mode|owner)=VALUE] URL [FILE]'
-		[.argc]=1
+		[.argc]=1-
 	)
 
 	flag.parse
@@ -1504,13 +1506,16 @@ file.download() {
 	local    url=${1?${FUNCNAME[0]}: missing argument};                shift
 	local -n file_download_dst_=${1?${FUNCNAME[0]}: missing argument}; shift
 
-	local tempfile
+	.say "Downloading $url..."
 
-	temp.file tempfile
-	must.success http.get "$url" >"$tempfile"
+	local download
+
+	temp.file download
+	must.success http.get "$url" >"$download"
+	must.success chmod 644 "$download"
 
 	# shellcheck disable=2034
-	file_download_dst_=$tempfile
+	file_download_dst_=$download
 }
 
 file.do_() {
@@ -1535,12 +1540,15 @@ file.do_() {
 	case $op in
 	copy)
 		must.success cp -a "$src" "$dst"
+		flag.true -quiet || .say "File copied to $dst."
 		;;
 	move)
 		must.success mv -f "$src" "$dst"
+		flag.true -quiet || .say "File moved to $dst."
 		;;
 	link)
 		file.ln "$src" "$dst"
+		flag.true -quiet || .say "File linked to $dst."
 		;;
 	*)
 		.bug "Unrecognized operation: $op"
@@ -1557,22 +1565,16 @@ file.dst_() {
 }
 
 file.install_() {
-	local url=${1?${FUNCNAME[0]}: missing argument}; shift
+	local src=${1?${FUNCNAME[0]}: missing argument}; shift
 	local dst=${1?${FUNCNAME[0]}: missing argument}; shift
 
-	local tempfile=
-
-	if url.is "$url" local; then
-		src=$url
+	if url.getable src; then
+		file.download "$src" src
+		file.do_ copy "$src" "$dst"
+		temp.clean src
 	else
-		temp.file tempfile
-		http.get "$url" >"$tempfile"
-		src=$tempfile
+		file.do_ copy "$src" "$dst"
 	fi
-
-	file.do_ copy "$src" "$dst"
-
-	temp.clean tempfile
 }
 
 # Private functions
@@ -1588,7 +1590,7 @@ file._do_args_() {
 		[-prefix]=
 
 		[.help]='[-(GROUP|MODE|OWNER|PREFIX)=VALUE] SRC [DST]'
-		[.argc]=1
+		[.argc]=1-
 	)
 
 	flag.parse
@@ -1646,21 +1648,23 @@ bin.install_() {
 	local url=$1
 
 	# shellcheck disable=1007
-	local bin= tempfile= tempdir=
+	local bin= temp_bin_file= temp_bin_dir=
 
-	if url.is "$url" local; then
-		bin=$url
+	if url.getable url; then
+		file.download "$url" temp_bin_file
+		bin=$temp_bin_file
 	else
-		file.download tempfile
-		bin=$tempfile
+		bin=$url
 	fi
 
-	if is.file compressed "$bin"; then
-		zip.unpack "$bin" tempdir
-		bin=$tempdir
+	if filetype.is "$bin" compressed; then
+		temp.dir temp_bin_dir
+
+		zip.unpack -force=true "$bin" "$temp_bin_dir"
+		bin=$temp_bin_dir
 	fi
 
-	local -a bins
+	local -a bins=()
 	bin._inspect "$bin" bins
 
 	if [[ ${#bins[@]} -eq 1 ]]; then
@@ -1678,7 +1682,7 @@ bin.install_() {
 		.die "No program found: $url"
 	fi
 
-	temp.clean tempfile tempdir
+	temp.clean temp_bin_file temp_bin_dir
 }
 
 # bin - Private functions
@@ -1690,10 +1694,10 @@ bin._inspect() {
 	if [[ -d $bin ]]; then
 		local file
 		for file in "$bin"/*; do
-			is.file program "$file" || continue
+			filetype.is "$file" program || continue
 			bin_inspect_+=("$file")
 		done
-	elif is.file program "$bin"; then
+	elif filetype.is "$bin" program; then
 		bin_inspect_+=("$file")
 	fi
 }
@@ -1807,8 +1811,8 @@ git.clone_() {
 	[[ -z ${_[.branch]:-}   ]] || opt+=(--branch "${_[.branch]}")
 
 	_func_() {
-		git clone "${opt[@]}" "$url" .
-		file.do_ copy . "$dst"
+		git clone "${opt[@]}" "$url" clone
+		file.do_ copy clone "$dst"
 	}
 
 	temp.inside _func_
@@ -2103,10 +2107,12 @@ deb.install() {
 
 	local arg
 	for arg; do
-		if url.getable "$arg"; then
-			urls+=("$arg")
+		local url=$arg
+
+		if url.getable url; then
+			urls+=("$url")
 		else
-			non_urls+=("$arg")
+			non_urls+=("$url")
 		fi
 	done
 
@@ -2256,15 +2262,15 @@ deb._dist_added() {
 deb._apt_key_add() {
 	local url=${1?${FUNCNAME[0]}: missing argument}; shift
 
-	local tempfile
-	temp.file tempfile
+	local temp_file
+	temp.file temp_file
 
-	http.get "$url" >"$tempfile" || .die "Couldn't get key file: $url"
+	http.get "$url" >"$temp_file" || .die "Couldn't get key file: $url"
 
 	local -a questioned_fingerprints installed_fingerprints
 
 	mapfile -t questioned_fingerprints < <(
-		gpg -nq --import --import-options import-show --with-colons "$tempfile" | awk -F: '$1 == "fpr" { print $10 }' 2>/dev/null
+		gpg -nq --import --import-options import-show --with-colons "$temp_file" | awk -F: '$1 == "fpr" { print $10 }' 2>/dev/null
 	)
 
 	# shellcheck disable=2034
@@ -2277,9 +2283,9 @@ deb._apt_key_add() {
 		.contains "$fingerprint" "${installed_fingerprints[@]}" || return 1
 	done
 
-	apt-key add "$tempfile"
+	apt-key add "$temp_file"
 
-	rm -f -- "$tempfile"
+	rm -f -- "$temp_file"
 }
 
 deb._missings() {
@@ -2384,8 +2390,8 @@ filetype.is() {
 	local -A _=(
 		[-zip]=false
 
-		[.help]='FILE'
-		[.argc]=1
+		[.help]='FILE TYPE'
+		[.argc]=2
 	)
 
 	flag.parse
@@ -2477,7 +2483,7 @@ zip.unpack() {
 		[-force]=false
 		[-clean]=false
 
-		[.help]='[-(force|clean)=BOOL] FILE'
+		[.help]='[-(force|clean)=BOOL] FILE [DIR]'
 		[.argc]=1-
 	)
 
@@ -2499,96 +2505,93 @@ zip.unpack() {
 }
 
 zip._unpack_.tar.gz() {
+	zip._prep_untar_ "$@"
+
 	local in=${1?${FUNCNAME[0]}: missing argument}; out=${2:-}
 
-	zip._prep_untar_
-
-	tar --strip-components=1 -zxvf "$in" -C "$out"
+	tar --strip-components=1 -zxf "$in" -C "$out"
 }
 
 zip._unpack_.tar.bz2() {
+	must.available bzip2 && zip._prep_untar_ "$@"
+
 	local in=${1?${FUNCNAME[0]}: missing argument}; out=${2:-}
 
-	zip._prep_untar_ bzip2
-
-	tar --strip-components=1 -jxvf "$in" -C "$out"
+	tar --strip-components=1 -jxf "$in" -C "$out"
 }
 
 zip._unpack_.tar.xz() {
+	must.available xz && zip._prep_untar_ "$@"
+
 	local in=${1?${FUNCNAME[0]}: missing argument}; out=${2:-}
 
-	zip._prep_untar_ xz
-
-	tar --strip-components=1 -Jxvf "$in" -C "$out"
+	tar --strip-components=1 -Jxf "$in" -C "$out"
 }
 
 zip._unpack_.tar.zst() {
+	must.available zstd && zip._prep_untar_ "$@"
+
 	local in=${1?${FUNCNAME[0]}: missing argument}; out=${2:-}
 
-	zip._prep_untar_ zstd
-
-	tar --strip-components=1 --zstd -xvf "$in" -C "$out"
+	tar --strip-components=1 --zstd -xf "$in" -C "$out"
 }
 
 zip._unpack_.zip() {
-	local in=${1?${FUNCNAME[0]}: missing argument}; out=${2:-}
+	must.available unzip && zip._prep_unzip_ "$@"
 
-	zip._prep_unzip_ unzip
+	local in=${1?${FUNCNAME[0]}: missing argument}; out=${2:-}
 
 	unzip -q -d "$out" "$in"
 }
 
 zip._unpack_.gz() {
+	must.available zcat && zip._prep_unzip_ "$@"
+
 	local in=${1?${FUNCNAME[0]}: missing argument}; out=${2:-}
 
 	zip._prep_unzip_ zcat
 
-	local tempfile
-	temp.file tempfile
+	local temp_file
+	temp.file temp_file
 
-	zcat "$in" >"$tempfile" && mv "$tempfile" "$out"
+	zcat "$in" >"$temp_file" && mv "$temp_file" "$out"
 }
 
 zip._unpack_.bz2() {
+	must.available bzcat && zip._prep_unzip_ "$@"
+
 	local in=${1?${FUNCNAME[0]}: missing argument}; out=${2:-}
 
-	zip._prep_unzip_ bzcat
+	local temp_file
+	temp.file temp_file
 
-	local tempfile
-	temp.file tempfile
-
-	bzcat "$in" >"$tempfile" && mv "$tempfile" "$out"
+	bzcat "$in" >"$temp_file" && mv "$temp_file" "$out"
 }
 
 zip._unpack_.xz() {
+	must.available unxz && zip._prep_unzip_ "$@"
+
 	local in=${1?${FUNCNAME[0]}: missing argument}; out=${2:-}
 
-	zip._prep_unzip_ unxz
+	local temp_file
+	temp.file temp_file
 
-	local tempfile
-	temp.file tempfile
-
-	unxz "$in" >"$tempfile" && mv "$tempfile" "$out"
+	unxz "$in" >"$temp_file" && mv "$temp_file" "$out"
 }
 
 zip._unpack_.zst() {
+	must.available zstdcat && zip._prep_unzip_ "$@"
+
 	local in=${1?${FUNCNAME[0]}: missing argument}; out=${2:-}
 
-	zip._prep_unzip_ zstdcat
+	local temp_file
+	temp.file temp_file
 
-	local tempfile
-	temp.file tempfile
-
-	zstdcat -f "$in" >"$tempfile" && mv "$tempfile" "$out"
+	zstdcat -f "$in" >"$temp_file" && mv "$temp_file" "$out"
 }
 
 zip._prep_unzip_() {
 	local in=${1?${FUNCNAME[0]}: missing argument}; out=${2:-}
-
-	local prog
-	for prog; do
-		must.available "$prog"
-	done
 
 	[[ -n $out ]] || out=${in%.*}
 
@@ -2603,11 +2606,6 @@ zip._prep_unzip_() {
 
 zip._prep_untar_() {
 	local in=${1?${FUNCNAME[0]}: missing argument}; out=${2:-}
-
-	local prog
-	for prog; do
-		must.available "$prog"
-	done
 
 	[[ -n $out ]] || out=${in%.tar.*}
 
@@ -2667,7 +2665,7 @@ if [[ ${UNDERSCORE_SOURCE:-} = true ]] || [[ "${BASH_SOURCE[0]}" = "$0" ]]; then
 		['os.codename']='Distribution codename'
 		['os.is']='Detect OS feature'
 		['url.is']='Assert URL feature'
-		['url.getable']='Assert URL is getable (via supported protocols)'
+		['url.getable']='Transform URL to a getable (via supported providers) form'
 		['http.get']='Get URL'
 		['http.is']='Assert URL response'
 		['file.install']='Install file from URL'
@@ -2888,6 +2886,7 @@ EOF
 		if ! .interactive && [[ $# -eq 0 ]]; then
 			.source
 		else
+			.init
 			app.dispatch "$@"
 		fi
 	}
