.

diff --git a/bin/_ b/bin/_
--- a/bin/_
+++ b/bin/_
@@ -7,16 +7,6 @@
 	command -v "${1?${FUNCNAME[0]}: missing argument}" &>/dev/null
 }
 
-.bug() {
-	if [[ $# -gt 0 ]]; then
-		echo -e >&2 "BUG: $*"
-	else
-		echo >&2 ""
-	fi
-
-	exit 127
-}
-
 .bye() {
 	if [[ $# -gt 0 ]]; then
 		echo -e >&2 "$*"
@@ -63,6 +53,47 @@
 	exit 1
 }
 
+.must() {
+	if [[ ${1:-} = -- ]]; then
+		shift
+
+		eval -- "${@?${FUNCNAME[0]}: missing argument}" || .die "Command failed: $*"
+	else
+		eval -- "${@:2}" || .die "${1?${FUNCNAME[0]}: missing argument}"
+	fi
+}
+
+.privileged() {
+	.must 'Root permissions required; use sudo(1)' [[ ${EUID:-} -eq 0 ]]
+}
+
+# Init
+
+# shellcheck disable=2034,2128
+.prelude() {
+	set -Eeuo pipefail; shopt -s nullglob; [[ -z ${TRACE:-} ]] || set -x; unset CDPATH; IFS=$' \t\n'
+
+	export LC_ALL=C.UTF-8 LANG=C.UTF-8
+
+	# Program name
+	declare -gr PROGNAME=${0##*/}
+
+	# Command names
+	declare -g CMDNAMES=()
+}
+
+.prelude
+
+.bug() {
+	if [[ $# -gt 0 ]]; then
+		echo -e >&2 "BUG: $*"
+	else
+		echo >&2 ""
+	fi
+
+	exit 127
+}
+
 .err() {
 	.out "$@" >&2
 }
@@ -91,26 +122,6 @@
 
 .interactive() {
 	[[  -t 1 ]]
-}
-
-.out() {
-	local arg
-
-	for arg; do
-		echo -e "$arg"
-	done
-
-	if .piped; then
-		cat
-	fi
-}
-
-.piped() {
-	[[ ! -t 0 ]]
-}
-
-.privileged() {
-	.must 'Root permissions required; use sudo(1)' [[ ${EUID:-} -eq 0 ]]
 }
 
 .load() {
@@ -147,14 +158,20 @@
 	unset _load_old_
 }
 
-.must() {
-	if [[ ${1:-} = -- ]]; then
-		shift
+.out() {
+	local arg
 
-		eval -- "${@?${FUNCNAME[0]}: missing argument}" || .die "Command failed: $*"
-	else
-		eval -- "${@:2}" || .die "${1?${FUNCNAME[0]}: missing argument}"
+	for arg; do
+		echo -e "$arg"
+	done
+
+	if .piped; then
+		cat
 	fi
+}
+
+.piped() {
+	[[ ! -t 0 ]]
 }
 
 .say() {
@@ -171,26 +188,10 @@
 	fi
 }
 
-# Init
-
-# shellcheck disable=2034,2128
-.prelude() {
-	set -Eeuo pipefail; shopt -s nullglob; [[ -z ${TRACE:-} ]] || set -x; unset CDPATH; IFS=$' \t\n'
-
-	export LC_ALL=C.UTF-8 LANG=C.UTF-8
-
-	# Program name
-	declare -gr PROGNAME=${0##*/}
-
-	# Command names
-	declare -g CMDNAMES=()
-}
-
-.prelude
-
 # _.sh - Underscore spesific functions
 
 # Core environment
+# shellcheck disable=2120
 .runtime() {
 	# Default variable as a hash
 	declare -gA _=()
@@ -270,6 +271,7 @@
 	export PATH SRCCACHE="${VOLATILE[src]}" SRCTEMP="${VOLATILE[tmp]}"
 }
 
+# shellcheck disable=2119
 .runtime
 
 # Libraries
@@ -4004,6 +4006,8 @@ if [[ "${BASH_SOURCE[0]}" = "$0" ]]; then
 
 					"$_SELF" "$@"
 				}
+
+				[[ $# -eq 0 ]] || _ "$@"
 EOF
 		else
 			.callback init
diff --git a/bin/t b/bin/t
--- a/bin/t
+++ b/bin/t
@@ -7,16 +7,6 @@
 	command -v "${1?${FUNCNAME[0]}: missing argument}" &>/dev/null
 }
 
-.bug() {
-	if [[ $# -gt 0 ]]; then
-		echo -e >&2 "BUG: $*"
-	else
-		echo >&2 ""
-	fi
-
-	exit 127
-}
-
 .bye() {
 	if [[ $# -gt 0 ]]; then
 		echo -e >&2 "$*"
@@ -63,6 +53,47 @@
 	exit 1
 }
 
+.must() {
+	if [[ ${1:-} = -- ]]; then
+		shift
+
+		eval -- "${@?${FUNCNAME[0]}: missing argument}" || .die "Command failed: $*"
+	else
+		eval -- "${@:2}" || .die "${1?${FUNCNAME[0]}: missing argument}"
+	fi
+}
+
+.privileged() {
+	.must 'Root permissions required; use sudo(1)' [[ ${EUID:-} -eq 0 ]]
+}
+
+# Init
+
+# shellcheck disable=2034,2128
+.prelude() {
+	set -Eeuo pipefail; shopt -s nullglob; [[ -z ${TRACE:-} ]] || set -x; unset CDPATH; IFS=$' \t\n'
+
+	export LC_ALL=C.UTF-8 LANG=C.UTF-8
+
+	# Program name
+	declare -gr PROGNAME=${0##*/}
+
+	# Command names
+	declare -g CMDNAMES=()
+}
+
+.prelude
+
+.bug() {
+	if [[ $# -gt 0 ]]; then
+		echo -e >&2 "BUG: $*"
+	else
+		echo >&2 ""
+	fi
+
+	exit 127
+}
+
 .err() {
 	.out "$@" >&2
 }
@@ -91,26 +122,6 @@
 
 .interactive() {
 	[[  -t 1 ]]
-}
-
-.out() {
-	local arg
-
-	for arg; do
-		echo -e "$arg"
-	done
-
-	if .piped; then
-		cat
-	fi
-}
-
-.piped() {
-	[[ ! -t 0 ]]
-}
-
-.privileged() {
-	.must 'Root permissions required; use sudo(1)' [[ ${EUID:-} -eq 0 ]]
 }
 
 .load() {
@@ -147,14 +158,20 @@
 	unset _load_old_
 }
 
-.must() {
-	if [[ ${1:-} = -- ]]; then
-		shift
+.out() {
+	local arg
 
-		eval -- "${@?${FUNCNAME[0]}: missing argument}" || .die "Command failed: $*"
-	else
-		eval -- "${@:2}" || .die "${1?${FUNCNAME[0]}: missing argument}"
+	for arg; do
+		echo -e "$arg"
+	done
+
+	if .piped; then
+		cat
 	fi
+}
+
+.piped() {
+	[[ ! -t 0 ]]
 }
 
 .say() {
@@ -171,26 +188,10 @@
 	fi
 }
 
-# Init
-
-# shellcheck disable=2034,2128
-.prelude() {
-	set -Eeuo pipefail; shopt -s nullglob; [[ -z ${TRACE:-} ]] || set -x; unset CDPATH; IFS=$' \t\n'
-
-	export LC_ALL=C.UTF-8 LANG=C.UTF-8
-
-	# Program name
-	declare -gr PROGNAME=${0##*/}
-
-	# Command names
-	declare -g CMDNAMES=()
-}
-
-.prelude
-
 # _.sh - Underscore spesific functions
 
 # Core environment
+# shellcheck disable=2120
 .runtime() {
 	# Default variable as a hash
 	declare -gA _=()
@@ -270,6 +271,7 @@
 	export PATH SRCCACHE="${VOLATILE[src]}" SRCTEMP="${VOLATILE[tmp]}"
 }
 
+# shellcheck disable=2119
 .runtime
 
 # meta - Meta functions
@@ -1359,16 +1361,6 @@ if [[ "${BASH_SOURCE[0]}" = "$0" ]]; then
 					command -v "${1?${FUNCNAME[0]}: missing argument}" &>/dev/null
 				}
 
-				.bug() {
-					if [[ $# -gt 0 ]]; then
-						echo -e >&2 "BUG: $*"
-					else
-						echo >&2 ""
-					fi
-
-					exit 127
-				}
-
 				.bye() {
 					if [[ $# -gt 0 ]]; then
 						echo -e >&2 "$*"
@@ -1415,90 +1407,6 @@ if [[ "${BASH_SOURCE[0]}" = "$0" ]]; then
 					exit 1
 				}
 
-				.err() {
-					.out "$@" >&2
-				}
-
-				.expired() {
-					local -i expiry=${1?${FUNCNAME[0]}: missing argument}; shift
-
-					case $expiry in
-					-1) return 1 ;;
-					0)  return 0 ;;
-					esac
-
-					local file
-					for file; do
-						local t=d
-
-						[[ -d $file ]] || t=f
-
-						if [[ -e $file ]] && [[ -z $(find "$file" -maxdepth 0 -type "$t" -mmin +"$expiry" 2>/dev/null) ]]; then
-							return 1
-						fi
-					done
-
-					return 0
-				}
-
-				.interactive() {
-					[[  -t 1 ]]
-				}
-
-				.out() {
-					local arg
-
-					for arg; do
-						echo -e "$arg"
-					done
-
-					if .piped; then
-						cat
-					fi
-				}
-
-				.piped() {
-					[[ ! -t 0 ]]
-				}
-
-				.privileged() {
-					.must 'Root permissions required; use sudo(1)' [[ ${EUID:-} -eq 0 ]]
-				}
-
-				.load() {
-					# shellcheck disable=2128
-					local _load_old_=$PWD
-
-					[[ -v _load_dirs_ ]] || declare -ag _load_dirs_=(
-						"$(dirname "$(readlink -f "$0")")"
-					)
-
-					local _load_src_
-
-					for _load_src_; do
-						builtin cd "${_load_dirs_[-1]}" || .die "Chdir error: ${_load_dirs_[-1]}"
-
-						local _load_src_found_
-
-						for _load_src_found_ in "$_load_src_" "$_load_src_".sh; do
-							if [[ -f $_load_src_found_ ]]; then
-								_load_src_found_=$(readlink -f "$_load_src_found_")
-
-								_load_dirs_+=("$(dirname "$_load_src_found_")")
-
-								builtin source "$_load_src_found_"
-							fi
-						done
-
-						unset _load_src_found_
-					done
-
-					unset _load_src_
-
-					builtin cd "$_load_old_" || .die "Chdir error: $_load_old_"
-					unset _load_old_
-				}
-
 				.must() {
 					if [[ ${1:-} = -- ]]; then
 						shift
@@ -1509,18 +1417,8 @@ if [[ "${BASH_SOURCE[0]}" = "$0" ]]; then
 					fi
 				}
 
-				.say() {
-					echo -e "${@-""}"
-				}
-
-				.should() {
-					if [[ ${1:-} = -- ]]; then
-						shift
-
-						eval -- "${@?${FUNCNAME[0]}: missing argument}" || .cry "Exit code $? is suppressed: $*"
-					else
-						eval -- "${@:2}" || .cry "${1?${FUNCNAME[0]}: missing argument}"
-					fi
+				.privileged() {
+					.must 'Root permissions required; use sudo(1)' [[ ${EUID:-} -eq 0 ]]
 				}
 
 				# Init
diff --git a/bin/tap b/bin/tap
--- a/bin/tap
+++ b/bin/tap
@@ -7,16 +7,6 @@
 	command -v "${1?${FUNCNAME[0]}: missing argument}" &>/dev/null
 }
 
-.bug() {
-	if [[ $# -gt 0 ]]; then
-		echo -e >&2 "BUG: $*"
-	else
-		echo >&2 ""
-	fi
-
-	exit 127
-}
-
 .bye() {
 	if [[ $# -gt 0 ]]; then
 		echo -e >&2 "$*"
@@ -63,6 +53,47 @@
 	exit 1
 }
 
+.must() {
+	if [[ ${1:-} = -- ]]; then
+		shift
+
+		eval -- "${@?${FUNCNAME[0]}: missing argument}" || .die "Command failed: $*"
+	else
+		eval -- "${@:2}" || .die "${1?${FUNCNAME[0]}: missing argument}"
+	fi
+}
+
+.privileged() {
+	.must 'Root permissions required; use sudo(1)' [[ ${EUID:-} -eq 0 ]]
+}
+
+# Init
+
+# shellcheck disable=2034,2128
+.prelude() {
+	set -Eeuo pipefail; shopt -s nullglob; [[ -z ${TRACE:-} ]] || set -x; unset CDPATH; IFS=$' \t\n'
+
+	export LC_ALL=C.UTF-8 LANG=C.UTF-8
+
+	# Program name
+	declare -gr PROGNAME=${0##*/}
+
+	# Command names
+	declare -g CMDNAMES=()
+}
+
+.prelude
+
+.bug() {
+	if [[ $# -gt 0 ]]; then
+		echo -e >&2 "BUG: $*"
+	else
+		echo >&2 ""
+	fi
+
+	exit 127
+}
+
 .err() {
 	.out "$@" >&2
 }
@@ -91,26 +122,6 @@
 
 .interactive() {
 	[[  -t 1 ]]
-}
-
-.out() {
-	local arg
-
-	for arg; do
-		echo -e "$arg"
-	done
-
-	if .piped; then
-		cat
-	fi
-}
-
-.piped() {
-	[[ ! -t 0 ]]
-}
-
-.privileged() {
-	.must 'Root permissions required; use sudo(1)' [[ ${EUID:-} -eq 0 ]]
 }
 
 .load() {
@@ -147,14 +158,20 @@
 	unset _load_old_
 }
 
-.must() {
-	if [[ ${1:-} = -- ]]; then
-		shift
+.out() {
+	local arg
 
-		eval -- "${@?${FUNCNAME[0]}: missing argument}" || .die "Command failed: $*"
-	else
-		eval -- "${@:2}" || .die "${1?${FUNCNAME[0]}: missing argument}"
+	for arg; do
+		echo -e "$arg"
+	done
+
+	if .piped; then
+		cat
 	fi
+}
+
+.piped() {
+	[[ ! -t 0 ]]
 }
 
 .say() {
@@ -170,107 +187,6 @@
 		eval -- "${@:2}" || .cry "${1?${FUNCNAME[0]}: missing argument}"
 	fi
 }
-
-# Init
-
-# shellcheck disable=2034,2128
-.prelude() {
-	set -Eeuo pipefail; shopt -s nullglob; [[ -z ${TRACE:-} ]] || set -x; unset CDPATH; IFS=$' \t\n'
-
-	export LC_ALL=C.UTF-8 LANG=C.UTF-8
-
-	# Program name
-	declare -gr PROGNAME=${0##*/}
-
-	# Command names
-	declare -g CMDNAMES=()
-}
-
-.prelude
-
-# _.sh - Underscore spesific functions
-
-# Core environment
-.runtime() {
-	# Default variable as a hash
-	declare -gA _=()
-
-	# shellcheck disable=2034
-	if [[ ${EUID:-} -eq 0 ]]; then
-		local volatile=${1:-/run/_} persistent=${2:-/usr/local}
-
-		[[ -v VOLATILE ]] || declare -Agr VOLATILE=(
-			[0]="$volatile"
-
-			[bin]="$volatile"/bin
-			[doc]="$volatile"/doc
-			[etc]="$volatile"/etc
-			[lib]="$volatile"/lib
-			[opt]="$volatile"/opt
-			[srv]="$volatile"/srv
-			[src]="$volatile"/src
-			[tmp]="$volatile"/tmp
-			[var]="$volatile"/var
-		)
-
-		[[ -v PERSISTENT ]] || declare -Agr PERSISTENT=(
-			[0]="$persistent"
-
-			[bin]="$persistent"/bin
-			[doc]="$persistent"/doc
-			[etc]="$persistent"/etc
-			[lib]="$persistent"/lib
-			[opt]=/opt
-			[src]="$persistent"/src
-			[srv]=/srv
-			[tmp]="${TMPDIR:-/var/local/tmp}"
-			[var]=/var/local
-		)
-	else
-		local volatile=${1:-${XDG_RUNTIME_DIR:-/run/user/"$EUID"/_}} persistent=${2:-~/.local}
-
-		[[ -v VOLATILE ]] || declare -Agr VOLATILE=(
-			[0]="$volatile"
-
-			[bin]="$volatile"/bin
-			[doc]="$volatile"/doc
-			[etc]="$volatile"/etc
-			[lib]="$volatile"/lib
-			[opt]="$volatile"/opt
-			[srv]="$volatile"/srv
-			[src]="$volatile"/src
-			[tmp]="$volatile"/tmp
-			[var]="$volatile"/var
-		)
-
-		[[ -v PERSISTENT ]] || declare -Agr PERSISTENT=(
-			[0]="$persistent"
-
-			[bin]="$persistent"/bin
-			[doc]="$persistent"/doc
-			[etc]="${XDG_CONFIG_HOME:-~/.config}"
-			[lib]="$persistent"/lib
-			[opt]="$persistent"/opt
-			[src]="$persistent"/src
-			[srv]="$persistent"/srv
-			[tmp]="${TMPDIR:-${XDG_CACHE_HOME:-~/.cache}/tmp}"
-			[var]="${XDG_CACHE_HOME:-~/.cache}"
-		)
-	fi
-
-	local path
-	for path in "${PERSISTENT[bin]}" "${VOLATILE[bin]}"; do
-		case ":$PATH:" in
-		*:"$path":*)	                     ;;
-		*)		PATH="$path":"$PATH" ;;
-		esac
-	done
-
-	# shellcheck disable=2128
-	export PATH SRCCACHE="${VOLATILE[src]}" SRCTEMP="${VOLATILE[tmp]}"
-}
-
-.runtime
 
 # color.sh - Colors
 
