.

diff --git a/bin/_ b/bin/_
--- a/bin/_
+++ b/bin/_
@@ -28,14 +28,16 @@
 	fi
 }
 
-.die() {
+.die-() {
 	if [[ $# -gt 0 ]]; then
 		echo -e >&2 "E: $*"
 	else
 		echo >&2 ""
 	fi
+}
 
-	exit 1
+.die() {
+	.die- "$@"; exit 1
 }
 
 .bug() {
@@ -403,9 +405,9 @@ flag._args_() {
 	fi
 
 	if   [[ -n ${lo:-} ]] && [[ $n -lt $lo ]]; then
-		.die 'Too few arguments' # FIXME
+		.die- 'Too few arguments'
 	elif [[ -n ${hi:-} ]] && [[ $n -gt $hi ]]; then
-		.die 'Too many arguments'
+		.die- 'Too many arguments'
 	else
 		return 0
 	fi
@@ -522,17 +524,6 @@ color._init
 
 # ui.sh - UI functions
 
-ui.caution()  { ui._echo "$@"; }
-ui.failure()  { ui._echo "$@"; }
-ui.headline() { ui._echo "$@"; }
-ui.info()     { ui._echo "$@"; }
-ui.network()  { ui._echo "$@"; }
-ui.panic()    { ui._echo "$@"; }
-ui.plain()    { ui._echo "$@"; }
-ui.question() { ui._echo "$@"; }
-ui.success()  { ui._echo "$@"; }
-ui.warning()  { ui._echo "$@"; }
-
 # Report bug and exit failure
 ui.bug() {
 	ui.panic "$@" >&2; exit 127
@@ -553,9 +544,14 @@ ui.cry() {
 	ui.warning "$@" >&2
 }
 
+# Print error messages without exiting
+ui.die-() {
+	ui.failure "$@" >&2
+}
+
 # Print error messages and exit failure
 ui.die() {
-	ui.failure "$@" >&2; exit 1
+	ui.die- "$@"; exit 1
 }
 
 # Print messages taking attention
@@ -604,6 +600,25 @@ ui._init() {
 	_sign[warning]='!';    _sign_color[warning]=+yellow;    _text_color[warning]=medium
 
 	color.expand _sign_color _text_color
+
+	ui.caution()  { ui._echo "$@"; }
+	ui.failure()  { ui._echo "$@"; }
+	ui.headline() { ui._echo "$@"; }
+	ui.info()     { ui._echo "$@"; }
+	ui.network()  { ui._echo "$@"; }
+	ui.panic()    { ui._echo "$@"; }
+	ui.plain()    { ui._echo "$@"; }
+	ui.question() { ui._echo "$@"; }
+	ui.success()  { ui._echo "$@"; }
+	ui.warning()  { ui._echo "$@"; }
+
+	.bug()  { ui.bug "$@"; }
+	.bye()  { ui.bye "$@"; }
+	.cry()  { ui.cry "$@"; }
+	.hey()  { ui.hey "$@"; }
+	.net()  { ui.net "$@"; }
+	.die()  { ui.die "$@"; }
+	.die-() { ui.die- "$@"; }
 }
 
 # shellcheck disable=2034,2154
@@ -618,15 +633,6 @@ ui._echo() {
 }
 
 ui._init
-
-shopt -s expand_aliases
-
-alias .bug=ui.bug
-alias .bye=ui.bye
-alias .cry=ui.cry
-alias .die=ui.die
-alias .hey=ui.hey
-alias .net=ui.net
 
 # must.sh - Guard functions
 
@@ -1017,7 +1023,7 @@ path.parse_() {
 # defer.sh - Deferred functions
 
 # shellcheck disable=2120
-defer.init() {
+.defer() {
 	if [[ -v _defer_initialized_ ]]; then
 		return
 	else
@@ -1095,7 +1101,7 @@ defer.init() {
 
 # Register files/directories to clean up at exit
 .clean() {
-	[[ -v _defer_initialized_ ]] || defer.init
+	[[ -v _defer_initialized_ ]] || .defer
 
 	_defer_clean_+=("$@")
 }
@@ -1503,7 +1509,8 @@ file.download() {
 	local download
 
 	temp.file download
-	must.success .net "Downloading $url" http.get "$url" >"$download"
+	.net "Downloading $url"
+	must.success http.get "$url" >"$download"
 	must.success chmod 644 "$download"
 
 	# shellcheck disable=2034
@@ -1608,7 +1615,7 @@ bin.install() {
 		[-prefix]="$_USR"/bin
 		[-name]=
 
-		[.help]='URL|FILE'
+		[.help]='[-name=NAME] [-prefix=DIR] URL|FILE'
 		[.argc]=1
 	)
 
@@ -1624,7 +1631,7 @@ bin.use() {
 		[-prefix]="$_RUN"/bin
 		[-name]=
 
-		[.help]='URL|FILE'
+		[.help]='[-name=NAME] [-prefix=DIR] URL|FILE'
 		[.argc]=1
 	)
 
@@ -2625,6 +2632,7 @@ if [[ ${UNDERSCORE_SOURCE:-} = true ]] || [[ "${BASH_SOURCE[0]}" = "$0" ]]; then
 		['ui.say']='Print messages on standard error'
 		['ui.bye']='Print messages on standard error and exit success'
 		['ui.cry']='Print warning messages on standard error'
+		['ui.die-']='Print error messages without exiting'
 		['ui.die']='Print error messages and exit failure'
 		['ui.hey']='Print messages taking attention'
 		['must.e']='Test -e'
@@ -2652,7 +2660,6 @@ if [[ ${UNDERSCORE_SOURCE:-} = true ]] || [[ "${BASH_SOURCE[0]}" = "$0" ]]; then
 		['array.join']='Join array with the given separator'
 		['array.dup']='Duplicate array'
 		['array.contains']='Array contains the given element'
-		['defer.init']='shellcheck disable=2120'
 		['temp.inside']='Execute command in temp dir'
 		['os.virtual']='Virtualization type'
 		['os.dist']='Distribution name'
diff --git a/bin/t b/bin/t
--- a/bin/t
+++ b/bin/t
@@ -28,14 +28,16 @@
 	fi
 }
 
-.die() {
+.die-() {
 	if [[ $# -gt 0 ]]; then
 		echo -e >&2 "E: $*"
 	else
 		echo >&2 ""
 	fi
+}
 
-	exit 1
+.die() {
+	.die- "$@"; exit 1
 }
 
 .bug() {
@@ -403,9 +405,9 @@ flag._args_() {
 	fi
 
 	if   [[ -n ${lo:-} ]] && [[ $n -lt $lo ]]; then
-		.die 'Too few arguments' # FIXME
+		.die- 'Too few arguments'
 	elif [[ -n ${hi:-} ]] && [[ $n -gt $hi ]]; then
-		.die 'Too many arguments'
+		.die- 'Too many arguments'
 	else
 		return 0
 	fi
@@ -648,17 +650,6 @@ color._init
 
 # ui.sh - UI functions
 
-ui.caution()  { ui._echo "$@"; }
-ui.failure()  { ui._echo "$@"; }
-ui.headline() { ui._echo "$@"; }
-ui.info()     { ui._echo "$@"; }
-ui.network()  { ui._echo "$@"; }
-ui.panic()    { ui._echo "$@"; }
-ui.plain()    { ui._echo "$@"; }
-ui.question() { ui._echo "$@"; }
-ui.success()  { ui._echo "$@"; }
-ui.warning()  { ui._echo "$@"; }
-
 # Report bug and exit failure
 ui.bug() {
 	ui.panic "$@" >&2; exit 127
@@ -679,9 +670,14 @@ ui.cry() {
 	ui.warning "$@" >&2
 }
 
+# Print error messages without exiting
+ui.die-() {
+	ui.failure "$@" >&2
+}
+
 # Print error messages and exit failure
 ui.die() {
-	ui.failure "$@" >&2; exit 1
+	ui.die- "$@"; exit 1
 }
 
 # Print messages taking attention
@@ -730,6 +726,25 @@ ui._init() {
 	_sign[warning]='!';    _sign_color[warning]=+yellow;    _text_color[warning]=medium
 
 	color.expand _sign_color _text_color
+
+	ui.caution()  { ui._echo "$@"; }
+	ui.failure()  { ui._echo "$@"; }
+	ui.headline() { ui._echo "$@"; }
+	ui.info()     { ui._echo "$@"; }
+	ui.network()  { ui._echo "$@"; }
+	ui.panic()    { ui._echo "$@"; }
+	ui.plain()    { ui._echo "$@"; }
+	ui.question() { ui._echo "$@"; }
+	ui.success()  { ui._echo "$@"; }
+	ui.warning()  { ui._echo "$@"; }
+
+	.bug()  { ui.bug "$@"; }
+	.bye()  { ui.bye "$@"; }
+	.cry()  { ui.cry "$@"; }
+	.hey()  { ui.hey "$@"; }
+	.net()  { ui.net "$@"; }
+	.die()  { ui.die "$@"; }
+	.die-() { ui.die- "$@"; }
 }
 
 # shellcheck disable=2034,2154
@@ -744,15 +759,6 @@ ui._echo() {
 }
 
 ui._init
-
-shopt -s expand_aliases
-
-alias .bug=ui.bug
-alias .bye=ui.bye
-alias .cry=ui.cry
-alias .die=ui.die
-alias .hey=ui.hey
-alias .net=ui.net
 
 readonly _TAP_VERSION_=13
 
@@ -1018,6 +1024,7 @@ if [[ ${OVERSCORE_SOURCE:-} = true ]] || [[ "${BASH_SOURCE[0]}" = "$0" ]]; then
 		['ui.say']='Print messages on standard error'
 		['ui.bye']='Print messages on standard error and exit success'
 		['ui.cry']='Print warning messages on standard error'
+		['ui.die-']='Print error messages without exiting'
 		['ui.die']='Print error messages and exit failure'
 		['ui.hey']='Print messages taking attention'
 		['tap.success']='Success'
@@ -1029,7 +1036,6 @@ if [[ ${OVERSCORE_SOURCE:-} = true ]] || [[ "${BASH_SOURCE[0]}" = "$0" ]]; then
 		['self.path']='Print self path'
 		['self.install']='Install self'
 		['app.dispatch']='shellcheck disable=2154'
-		['defer.init']='shellcheck disable=2120'
 		['temp.inside']='Execute command in temp dir'
 		['assert.ok']='Assert command succeed'
 		['assert.notok']='Assert command failed'
@@ -1162,14 +1168,16 @@ if [[ ${OVERSCORE_SOURCE:-} = true ]] || [[ "${BASH_SOURCE[0]}" = "$0" ]]; then
 			fi
 		}
 
-		.die() {
+		.die-() {
 			if [[ $# -gt 0 ]]; then
 				echo -e >&2 "E: $*"
 			else
 				echo >&2 ""
 			fi
+		}
 
-			exit 1
+		.die() {
+			.die- "$@"; exit 1
 		}
 
 		.bug() {
@@ -1241,7 +1249,7 @@ if [[ ${OVERSCORE_SOURCE:-} = true ]] || [[ "${BASH_SOURCE[0]}" = "$0" ]]; then
 		# defer.sh - Deferred functions
 
 		# shellcheck disable=2120
-		defer.init() {
+		.defer() {
 			if [[ -v _defer_initialized_ ]]; then
 				return
 			else
@@ -1319,7 +1327,7 @@ if [[ ${OVERSCORE_SOURCE:-} = true ]] || [[ "${BASH_SOURCE[0]}" = "$0" ]]; then
 
 		# Register files/directories to clean up at exit
 		.clean() {
-			[[ -v _defer_initialized_ ]] || defer.init
+			[[ -v _defer_initialized_ ]] || .defer
 
 			_defer_clean_+=("$@")
 		}
