.

diff --git a/bin/t b/bin/t
--- a/bin/t
+++ b/bin/t
@@ -177,6 +177,101 @@
 
 .prelude
 
+# assert.sh - Assertions
+
+assert.err() {
+	local -n assert_err_=${1?${FUNCNAME[0]}: missing argument}; shift
+
+	# shellcheck disable=2034
+	assert_err_=("$(
+		hope -success=false "$@"
+	)")
+}
+
+assert.fail() {
+	false
+}
+
+assert.is() {
+	local -n assert_is_=${1?${FUNCNAME[0]}: missing argument}; shift
+
+	local got=${1?${FUNCNAME[0]}: missing argument};      shift
+	local expected=${1?${FUNCNAME[0]}: missing argument}; shift
+
+	# shellcheck disable=2034
+	assert_is_="Got '$got' where expected '$expected'"
+
+	[[ $got = "$expected" ]]
+}
+
+assert.isnt() {
+	local -n assert_isnt_=${1?${FUNCNAME[0]}: missing argument}; shift
+
+	local got=${1?${FUNCNAME[0]}: missing argument};      shift
+	local expected=${1?${FUNCNAME[0]}: missing argument}; shift
+
+	# shellcheck disable=2034
+	assert_isnt_=("Got unexpected '$got'")
+
+	[[ $got != "$expected" ]]
+}
+
+assert.like() {
+	local -n assert_like_=${1?${FUNCNAME[0]}: missing argument}; shift
+
+	local got=${1?${FUNCNAME[0]}: missing argument};      shift
+	local expected=${1?${FUNCNAME[0]}: missing argument}; shift
+
+	# shellcheck disable=2034
+	assert_like_=("Got '$got' where expected to match with '$expected'")
+
+	[[ $got =~ $expected ]]
+}
+
+assert.notok() {
+	local -n assert_notok_=${1?${FUNCNAME[0]}: missing argument}; shift
+
+	# shellcheck disable=2034
+	assert_notok_="Command expected to fail but succeeded: $*"
+
+	! eval -- "$@"
+}
+
+# shellcheck disable=2034
+assert.ok() {
+	local -n assert_ok_=${1?${FUNCNAME[0]}: missing argument}; shift
+
+	assert_ok_="Command expected to succeed but failed: $*"
+
+	eval -- "$@"
+}
+
+assert.out() {
+	local -n assert_out_=${1?${FUNCNAME[0]}: missing argument}; shift
+
+	# shellcheck disable=2034
+	assert_out_=("$(
+		hope -success=true "$@"
+	)")
+}
+
+assert.pass() {
+	true
+}
+
+assert.unlike() {
+	local -n assert_unlike_=${1?${FUNCNAME[0]}: missing argument}; shift
+
+	local got=${1?${FUNCNAME[0]}: missing argument};      shift
+	local expected=${1?${FUNCNAME[0]}: missing argument}; shift
+
+	# shellcheck disable=2034
+	assert_unlike_=("Got '$got' where expected to unmatch with '$expected'")
+
+	[[ ! $got =~ $expected ]]
+}
+
+
 # color.sh - Colors
 
 color.code() {
@@ -281,6 +376,91 @@ color.init_() {
 }
 
 color.init_
+
+# defer.sh - Deferred functions
+
+# Register files/directories to clean up at exit
+.clean() {
+	[[ -v _defer_initialized_ ]] || .defer
+
+	_defer_clean_+=("$@")
+}
+
+# Trap defer setup
+# shellcheck disable=2120
+.defer() {
+	if [[ -v _defer_initialized_ ]]; then
+		return
+	else
+		_defer_initialized_=true
+
+		declare -ag _defer_clean_=()
+
+		if [[ -n $(builtin trap -p 2>/dev/null) ]]; then
+			.cry 'Trap already taken.'
+
+			return
+		fi
+	fi
+
+	local -a signals=("$@")
+	[[ $# -gt 0 ]] || signals=(EXIT HUP INT KILL QUIT TERM)
+
+	local signal
+	for signal in "${signals[@]}"; do
+		# shellcheck disable=2064
+		builtin trap "_defer_ $signal" "$signal"
+	done
+
+	# Prevent using trap
+	trap() {
+		.bug 'Using trap is forbidden; please use defer.* functions.'
+	}
+
+	# shellcheck disable=2139
+	alias .untrap="trap - ${signals[*]}"
+
+	_defer_() {
+		local -r SIG=$1 ERR=$?
+
+		local -a _defer_funcs_
+
+		mapfile -t _defer_funcs_ < <(
+			shopt -s extdebug
+
+			declare -F | grep 'declare -f defer[.]' | awk '{ print $3 }' |
+			while read -r func; do declare -F "$func"; done |
+			sort -t' ' -k2 -n | awk '
+				$1 !~ /defer[.]early|defer[.]late/ {
+					print $1
+				}
+			'
+		)
+
+		! .callable defer.early || defer.early
+
+		local func
+		for func in "${_defer_funcs_[@]}"; do
+			"$func" || [[ $SIG = INT ]] || [[ $SIG = QUIT ]] || .cry "Deferred function failed: $func"
+		done
+
+		if [[ -v _defer_clean_ ]] && [[ "${#_defer_clean_[@]}" -gt 0 ]]; then
+			rm -rf -- "${_defer_clean_[@]}"
+		fi
+
+		! .callable defer.late || defer.late
+
+		builtin trap - EXIT
+
+		if [[ $SIG = INT ]] || [[ $SIG = QUIT ]]; then
+			builtin trap - "$SIG"; kill -s "$SIG" "$$"
+		fi
+
+		return "$ERR"
+	}
+
+	readonly -f _defer_
+}
 
 # flag.sh - Flag handling
 
@@ -735,7 +915,7 @@ t:go() {
 # cmd/t - Protected functions
 
 t:assert_() {
-	local assert=assert.${FUNCNAME[1]#*.}
+	local assert=assert.${FUNCNAME[1]#*:}
 
 	local -a args
 
@@ -824,18 +1004,18 @@ if [[ "${BASH_SOURCE[0]}" = "$0" ]]; then
 	)
 
 	declare -Ag _command=(
-		['t err']='t:err'
-		['t fail']='t:fail'
-		['t go']='t:go'
-		['t is']='t:is'
-		['t isnt']='t:isnt'
-		['t like']='t:like'
-		['t notok']='t:notok'
-		['t ok']='t:ok'
-		['t out']='t:out'
-		['t pass']='t:pass'
-		['t temp']='t:temp'
-		['t unlike']='t:unlike'
+		['err']='t:err'
+		['fail']='t:fail'
+		['go']='t:go'
+		['is']='t:is'
+		['isnt']='t:isnt'
+		['like']='t:like'
+		['notok']='t:notok'
+		['ok']='t:ok'
+		['out']='t:out'
+		['pass']='t:pass'
+		['temp']='t:temp'
+		['unlike']='t:unlike'
 		['version']=':version'
 	)
 
@@ -1021,6 +1201,101 @@ if [[ "${BASH_SOURCE[0]}" = "$0" ]]; then
 			}
 
 			.prelude
+
+			# assert.sh - Assertions
+
+			assert.err() {
+				local -n assert_err_=${1?${FUNCNAME[0]}: missing argument}; shift
+
+				# shellcheck disable=2034
+				assert_err_=("$(
+					hope -success=false "$@"
+				)")
+			}
+
+			assert.fail() {
+				false
+			}
+
+			assert.is() {
+				local -n assert_is_=${1?${FUNCNAME[0]}: missing argument}; shift
+
+				local got=${1?${FUNCNAME[0]}: missing argument};      shift
+				local expected=${1?${FUNCNAME[0]}: missing argument}; shift
+
+				# shellcheck disable=2034
+				assert_is_="Got '$got' where expected '$expected'"
+
+				[[ $got = "$expected" ]]
+			}
+
+			assert.isnt() {
+				local -n assert_isnt_=${1?${FUNCNAME[0]}: missing argument}; shift
+
+				local got=${1?${FUNCNAME[0]}: missing argument};      shift
+				local expected=${1?${FUNCNAME[0]}: missing argument}; shift
+
+				# shellcheck disable=2034
+				assert_isnt_=("Got unexpected '$got'")
+
+				[[ $got != "$expected" ]]
+			}
+
+			assert.like() {
+				local -n assert_like_=${1?${FUNCNAME[0]}: missing argument}; shift
+
+				local got=${1?${FUNCNAME[0]}: missing argument};      shift
+				local expected=${1?${FUNCNAME[0]}: missing argument}; shift
+
+				# shellcheck disable=2034
+				assert_like_=("Got '$got' where expected to match with '$expected'")
+
+				[[ $got =~ $expected ]]
+			}
+
+			assert.notok() {
+				local -n assert_notok_=${1?${FUNCNAME[0]}: missing argument}; shift
+
+				# shellcheck disable=2034
+				assert_notok_="Command expected to fail but succeeded: $*"
+
+				! eval -- "$@"
+			}
+
+			# shellcheck disable=2034
+			assert.ok() {
+				local -n assert_ok_=${1?${FUNCNAME[0]}: missing argument}; shift
+
+				assert_ok_="Command expected to succeed but failed: $*"
+
+				eval -- "$@"
+			}
+
+			assert.out() {
+				local -n assert_out_=${1?${FUNCNAME[0]}: missing argument}; shift
+
+				# shellcheck disable=2034
+				assert_out_=("$(
+					hope -success=true "$@"
+				)")
+			}
+
+			assert.pass() {
+				true
+			}
+
+			assert.unlike() {
+				local -n assert_unlike_=${1?${FUNCNAME[0]}: missing argument}; shift
+
+				local got=${1?${FUNCNAME[0]}: missing argument};      shift
+				local expected=${1?${FUNCNAME[0]}: missing argument}; shift
+
+				# shellcheck disable=2034
+				assert_unlike_=("Got '$got' where expected to unmatch with '$expected'")
+
+				[[ ! $got =~ $expected ]]
+			}
+
 
 			# defer.sh - Deferred functions
 
@@ -1242,7 +1517,7 @@ if [[ "${BASH_SOURCE[0]}" = "$0" ]]; then
 			# cmd/t - Protected functions
 
 			t:assert_() {
-				local assert=assert.${FUNCNAME[1]#*.}
+				local assert=assert.${FUNCNAME[1]#*:}
 
 				local -a args
 
@@ -1312,8 +1587,8 @@ if [[ "${BASH_SOURCE[0]}" = "$0" ]]; then
 
 				[[ $cmd =~ ^[a-z][a-z0-9-]+$ ]] || .die "Invalid command name: $cmd"
 
-				if .callable t."$cmd"; then
-					t."$cmd" "$@"
+				if .callable t:"$cmd"; then
+					t:"$cmd" "$@"
 				else
 					tap "$@"
 				fi
@@ -1321,7 +1596,7 @@ if [[ "${BASH_SOURCE[0]}" = "$0" ]]; then
 
 			[[ $# -eq 0 ]] || .load "$@"
 
-			tap startup "${BASH_SOURCE[1]}"
+			[[ -z "${BASH_SOURCE[1]:-}" ]] || tap startup "${BASH_SOURCE[1]}"
 EOF
 	}
 
