.

diff --git a/bin/t b/bin/t
--- a/bin/t
+++ b/bin/t
@@ -24,12 +24,16 @@
 	local arg
 
 	for arg; do
-		echo -e >&2 "$arg"
+		echo -e "$arg"
 	done
 
 	if .piped; then
-		cat >&2
+		cat
 	fi
+}
+
+.err() {
+	.out "$@" >&2
 }
 
 .cry() {
@@ -333,167 +337,6 @@ flag._post_() {
 	flag.usage_ 1
 }
 
-# color.sh - Colors
-
-# shellcheck disable=2034
-color._init() {
-	declare -Ag _color=(
-		# Basic colors with variants - prefix +: bold, prefix -: dim, suffix -: reverse
-
-		[black]='\e[38;5;8m'          [+black]='\e[1m\e[38;5;8m'     [-black]='\e[38;5;0m'
-		[black-]='\e[48;5;8m'         [+black-]='\e[1m\e[48;5;8m'    [-black-]='\e[48;5;0m'
-
-		[blue]='\e[38;5;12m'          [+blue]='\e[1m\e[38;5;12m'     [-blue]='\e[38;5;4m'
-		[blue-]='\e[48;5;12m'         [+blue-]='\e[1m\e[48;5;12m'    [-blue-]='\e[48;5;4m'
-
-		[cyan]='\e[38;5;14m'          [+cyan]='\e[1m\e[38;5;14m'     [-cyan]='\e[38;5;6m'
-		[cyan-]='\e[48;5;14m'         [+cyan-]='\e[1m\e[48;5;14m'    [-cyan-]='\e[48;5;6m'
-
-		[green]='\e[38;5;10m'         [+green]='\e[1m\e[38;5;10m'    [-green]='\e[38;5;2m'
-		[green-]='\e[48;5;10m'        [+green-]='\e[1m\e[48;5;10m'   [-green-]='\e[48;5;2m'
-
-		[magenta]='\e[38;5;13m'       [+magenta]='\e[1m\e[38;5;13m'  [-magenta]='\e[38;5;5m'
-		[magenta-]='\e[48;5;13m'      [+magenta-]='\e[1m\e[48;5;13m' [-magenta-]='\e[48;5;5m'
-
-		[red]='\e[38;5;9m'            [+red]='\e[1m\e[38;5;9m'       [-red]='\e[38;5;1m'
-		[red-]='\e[48;5;9m'           [+red-]='\e[1m\e[48;5;9m'      [-red-]='\e[48;5;1m'
-
-		[white]='\e[38;5;15m'         [+white]='\e[1m\e[38;5;15m'    [-white]='\e[38;5;7m'
-		[white-]='\e[48;5;15m'        [+white-]='\e[1m\e[48;5;15m'   [-white-]='\e[48;5;7m'
-
-		[yellow]='\e[38;5;11m'        [+yellow]='\e[1m\e[38;5;11m'   [-yellow]='\e[38;5;3m'
-		[yellow-]='\e[48;5;11m'       [+yellow-]='\e[1m\e[48;5;11m'  [-yellow-]='\e[48;5;3m'
-
-		# Attributes
-
-		[bold]='\e[1m'                [dark]='\e[2m'                 [underlined]='\e[4m'
-		[blink]='\e[5m'               [reverse]='\e[7m'              [reset]='\e[0m'
-
-		# Priority aliases
-		[high]='\e[1m'                [medium]=''                    [low]='\e[2m'
-	)
-}
-
-color.expand() {
-	while [[ $# -gt 0 ]]; do
-		local -n color_expand_=${1?missing argument}
-		shift
-
-		local key value
-		for key in "${!color_expand_[@]}"; do
-			value=${color_expand_[$key]}
-
-			color_expand_[$key]=${_color[$value]}
-		done
-	done
-}
-
-color.setup() {
-	while [[ $# -gt 0 ]]; do
-		local key=${1%%=*}; value=${1#*=}
-
-		if [[ -n ${_color[$value]:-} ]]; then
-			_color[$key]=${_color[$value]}
-		else
-			_color[$key]=$value
-		fi
-
-		shift
-	done
-}
-
-color.code() {
-	local code="${_color[${1?missing argument}]:-}"
-
-	[[ -n $code ]] || .bug "No such color: $1"
-
-	echo -en "$code"
-}
-
-color._init
-
-# ui.sh - UI functions
-
-# shellcheck disable=2034,2154
-ui._init() {
-	declare -Ag _sign _sign_color _text_color
-
-	# Style
-
-	_sign[caution]='★';    _sign_color[caution]=+cyan;      _text_color[caution]=high
-	_sign[error]='✗';      _sign_color[error]=+red;         _text_color[error]=high
-	_sign[headline]='>';   _sign_color[headline]=+cyan;     _text_color[headline]=high
-	_sign[info]='ℹ';       _sign_color[info]=-yellow;       _text_color[info]=low
-	_sign[panic]='✖';      _sign_color[panic]=red;          _text_color[panic]=high
-	_sign[plain]=' ';      _sign_color[plain]=+white;       _text_color[plain]=medium
-	_sign[question]='?';   _sign_color[question]=+yellow;   _text_color[question]=high
-	_sign[success]='✓';    _sign_color[success]=+green;     _text_color[success]=high
-	_sign[warning]='!';    _sign_color[warning]=+yellow;    _text_color[warning]=medium
-
-	color.expand _sign_color _text_color
-}
-
-# shellcheck disable=2034,2154
-ui._out() {
-	local name=${FUNCNAME[1]#*.}
-
-	local sign=${_sign[$name]}
-
-	local sign_color=${_sign_color[$name]} text_color=${_text_color[$name]} reset=${_color[reset]}
-
-	echo -e "${sign_color}${sign}${reset} ${text_color}$*${reset}"
-}
-
-ui.panic()    { ui._out "$@"; }
-ui.caution()  { ui._out "$@"; }
-ui.error()    { ui._out "$@"; }
-ui.headline() { ui._out "$@"; }
-ui.info()     { ui._out "$@"; }
-ui.plain()    { ui._out "$@"; }
-ui.question() { ui._out "$@"; }
-ui.success()  { ui._out "$@"; }
-ui.warning()  { ui._out "$@"; }
-
-# Report bug and exit failure
-ui.bug() {
-	ui.panic "$@" >&2; exit 127
-}
-
-# Print messages on standard error
-ui.say() {
-	ui.plain "$@" >&2
-}
-
-# Print messages on standard error and exit success
-ui.bye() {
-	ui.plain "$@" >&2; exit 0
-}
-
-# Print warning messages on standard error
-ui.cry() {
-	ui.warning "$@" >&2
-}
-
-# Print error messages and exit failure
-ui.die() {
-	ui.error "$@" >&2; exit 1
-}
-
-# Print messages taking attention
-ui.hey() {
-	ui.headline "$@" >&2
-}
-
-ui._init
-
-shopt -s expand_aliases
-
-alias .bug=ui.bug
-alias .bye=ui.bye
-alias .cry=ui.cry
-alias .die=ui.die
-alias .hey=ui.hey
-
 # must.sh - Guard functions
 
 # Test -e
@@ -620,6 +463,240 @@ must.interactive() {
 	.interactive || .die "$message"
 }
 
+# color.sh - Colors
+
+# shellcheck disable=2034
+color._init() {
+	declare -Ag _color=(
+		# Basic colors with variants - prefix +: bold, prefix -: dim, suffix -: reverse
+
+		[black]='\e[38;5;8m'          [+black]='\e[1m\e[38;5;8m'     [-black]='\e[38;5;0m'
+		[black-]='\e[48;5;8m'         [+black-]='\e[1m\e[48;5;8m'    [-black-]='\e[48;5;0m'
+
+		[blue]='\e[38;5;12m'          [+blue]='\e[1m\e[38;5;12m'     [-blue]='\e[38;5;4m'
+		[blue-]='\e[48;5;12m'         [+blue-]='\e[1m\e[48;5;12m'    [-blue-]='\e[48;5;4m'
+
+		[cyan]='\e[38;5;14m'          [+cyan]='\e[1m\e[38;5;14m'     [-cyan]='\e[38;5;6m'
+		[cyan-]='\e[48;5;14m'         [+cyan-]='\e[1m\e[48;5;14m'    [-cyan-]='\e[48;5;6m'
+
+		[green]='\e[38;5;10m'         [+green]='\e[1m\e[38;5;10m'    [-green]='\e[38;5;2m'
+		[green-]='\e[48;5;10m'        [+green-]='\e[1m\e[48;5;10m'   [-green-]='\e[48;5;2m'
+
+		[magenta]='\e[38;5;13m'       [+magenta]='\e[1m\e[38;5;13m'  [-magenta]='\e[38;5;5m'
+		[magenta-]='\e[48;5;13m'      [+magenta-]='\e[1m\e[48;5;13m' [-magenta-]='\e[48;5;5m'
+
+		[red]='\e[38;5;9m'            [+red]='\e[1m\e[38;5;9m'       [-red]='\e[38;5;1m'
+		[red-]='\e[48;5;9m'           [+red-]='\e[1m\e[48;5;9m'      [-red-]='\e[48;5;1m'
+
+		[white]='\e[38;5;15m'         [+white]='\e[1m\e[38;5;15m'    [-white]='\e[38;5;7m'
+		[white-]='\e[48;5;15m'        [+white-]='\e[1m\e[48;5;15m'   [-white-]='\e[48;5;7m'
+
+		[yellow]='\e[38;5;11m'        [+yellow]='\e[1m\e[38;5;11m'   [-yellow]='\e[38;5;3m'
+		[yellow-]='\e[48;5;11m'       [+yellow-]='\e[1m\e[48;5;11m'  [-yellow-]='\e[48;5;3m'
+
+		# Attributes
+
+		[bold]='\e[1m'                [dark]='\e[2m'                 [underlined]='\e[4m'
+		[blink]='\e[5m'               [reverse]='\e[7m'              [reset]='\e[0m'
+
+		# Priority aliases
+		[high]='\e[1m'                [medium]=''                    [low]='\e[2m'
+	)
+}
+
+color.expand() {
+	while [[ $# -gt 0 ]]; do
+		local -n color_expand_=${1?missing argument}
+		shift
+
+		local key value
+		for key in "${!color_expand_[@]}"; do
+			value=${color_expand_[$key]}
+
+			color_expand_[$key]=${_color[$value]}
+		done
+	done
+}
+
+color.setup() {
+	while [[ $# -gt 0 ]]; do
+		local key=${1%%=*}; value=${1#*=}
+
+		if [[ -n ${_color[$value]:-} ]]; then
+			_color[$key]=${_color[$value]}
+		else
+			_color[$key]=$value
+		fi
+
+		shift
+	done
+}
+
+color.code() {
+	local code="${_color[${1?missing argument}]:-}"
+
+	[[ -n $code ]] || .bug "No such color: $1"
+
+	echo -en "$code"
+}
+
+color.out() {
+	local color=${1?missing argument}
+	shift
+
+	local code reset
+	code=$(color.code "$color")
+	reset=$(color.code reset)
+
+	echo -en "$code"
+	.out
+	echo -en "$reset"
+}
+
+color._init
+
+# ui.sh - UI functions
+
+# shellcheck disable=2034,2154
+ui._init() {
+	declare -Ag _sign _sign_color _text_color
+
+	# Style
+
+	_sign[caution]='★';    _sign_color[caution]=+cyan;      _text_color[caution]=high
+	_sign[failure]='✗';    _sign_color[failure]=+red;       _text_color[failure]=high
+	_sign[headline]='>';   _sign_color[headline]=+cyan;     _text_color[headline]=high
+	_sign[info]='ℹ';       _sign_color[info]=-yellow;       _text_color[info]=low
+	_sign[panic]='✖';      _sign_color[panic]=red;          _text_color[panic]=high
+	_sign[plain]=' ';      _sign_color[plain]=+white;       _text_color[plain]=medium
+	_sign[question]='?';   _sign_color[question]=+yellow;   _text_color[question]=high
+	_sign[success]='✓';    _sign_color[success]=+green;     _text_color[success]=high
+	_sign[warning]='!';    _sign_color[warning]=+yellow;    _text_color[warning]=medium
+
+	color.expand _sign_color _text_color
+}
+
+# shellcheck disable=2034,2154
+ui._echo() {
+	local name=${FUNCNAME[1]#*.}
+
+	local sign=${_sign[$name]}
+
+	local sign_color=${_sign_color[$name]} text_color=${_text_color[$name]} reset=${_color[reset]}
+
+	echo -e "${sign_color}${sign}${reset} ${text_color}$*${reset}"
+}
+
+ui.panic()    { ui._echo "$@"; }
+ui.caution()  { ui._echo "$@"; }
+ui.failure()  { ui._echo "$@"; }
+ui.headline() { ui._echo "$@"; }
+ui.info()     { ui._echo "$@"; }
+ui.plain()    { ui._echo "$@"; }
+ui.question() { ui._echo "$@"; }
+ui.success()  { ui._echo "$@"; }
+ui.warning()  { ui._echo "$@"; }
+
+# Report bug and exit failure
+ui.bug() {
+	ui.panic "$@" >&2; exit 127
+}
+
+# Print messages on standard error
+ui.say() {
+	ui.plain "$@" >&2
+}
+
+# Print messages on standard error and exit success
+ui.bye() {
+	ui.plain "$@" >&2; exit 0
+}
+
+# Print warning messages on standard error
+ui.cry() {
+	ui.warning "$@" >&2
+}
+
+# Print error messages and exit failure
+ui.die() {
+	ui.failure "$@" >&2; exit 1
+}
+
+# Print messages taking attention
+ui.hey() {
+	ui.headline "$@" >&2
+}
+
+ui._init
+
+shopt -s expand_aliases
+
+alias .bug=ui.bug
+alias .bye=ui.bye
+alias .cry=ui.cry
+alias .die=ui.die
+alias .hey=ui.hey
+
+ui.out() {
+	local name=$1
+	shift
+
+	local sign=${_sign[$name]}
+
+	local sign_color=${_sign_color[$name]} text_color=${_text_color[$name]} reset=${_color[reset]}
+
+	echo -en "${sign_color}${sign}${reset} "
+	.out
+	echo -en "$reset "
+}
+
+tap.suite_starting() {
+	local file=$1
+
+	echo "# Running tests in $file"
+}
+
+tap.starting() {
+	echo -n
+}
+
+tap.pending() {
+	local test=$1
+
+	echo -n ok | ui.out warning
+	echo -n "$test" | color.out +blue
+	echo ' # skip test to be written' | color.out +yellow
+}
+
+# Success
+tap.success() {
+	local test=$1
+
+	echo -n ok | ui.out success
+	echo "$test" | color.out +blue
+}
+
+# Failure
+tap.failure() {
+	local test=$1 msg=${2:-}
+
+	echo -n 'not ok' | ui.out failure
+	echo "$test" | color.out +blue
+	[[ -z ${msg:-} ]] || printf -- "%s\n" "$msg" | sed -u -e 's/^/# /'
+}
+
+tap.out() {
+	sed 's:^:# out> :' | color.out +green
+}
+
+tap.err() {
+	sed 's:^:# err> :' | color.out +red
+}
+
+tap.stack() {
+	sed 's:^:# :' | color.out yellow
+}
+
 # self.sh - Functions related to program itself
 
 # Print self
@@ -684,12 +761,6 @@ self.install() {
 
 if [[ ${OVERSCORE_SOURCE:-} = true ]] || [[ "${BASH_SOURCE[0]}" = "$0" ]]; then
 	declare -Ag _help=(
-		['ui.bug']='Report bug and exit failure'
-		['ui.say']='Print messages on standard error'
-		['ui.bye']='Print messages on standard error and exit success'
-		['ui.cry']='Print warning messages on standard error'
-		['ui.die']='Print error messages and exit failure'
-		['ui.hey']='Print messages taking attention'
 		['must.e']='Test -e'
 		['must.f']='Test -f'
 		['must.d']='Test -d'
@@ -707,6 +778,14 @@ if [[ ${OVERSCORE_SOURCE:-} = true ]] || [[ "${BASH_SOURCE[0]}" = "$0" ]]; then
 		['must.callable']='Function must exist'
 		['must.piped']='Stdin must exist'
 		['must.interactive']='Stdout must exist'
+		['ui.bug']='Report bug and exit failure'
+		['ui.say']='Print messages on standard error'
+		['ui.bye']='Print messages on standard error and exit success'
+		['ui.cry']='Print warning messages on standard error'
+		['ui.die']='Print error messages and exit failure'
+		['ui.hey']='Print messages taking attention'
+		['tap.success']='Success'
+		['tap.failure']='Failure'
 		['self']='Print self'
 		['self.version']='Print self version'
 		['self.name']='Print self name'
@@ -722,6 +801,9 @@ if [[ ${OVERSCORE_SOURCE:-} = true ]] || [[ "${BASH_SOURCE[0]}" = "$0" ]]; then
 		['is']='test.is'
 		['notok']='test.notok'
 		['ok']='test.ok'
+		['success']='tap.success'
+		['failure']='tap.failure'
+		['err']='tap.err'
 	)
 
 	.usage() {
@@ -762,11 +844,12 @@ if [[ ${OVERSCORE_SOURCE:-} = true ]] || [[ "${BASH_SOURCE[0]}" = "$0" ]]; then
 
 		while [[ $# -gt 0 ]]; do
 			try+=("$1")
-			shift
 
 			[[ -n ${_command[${try[*]}]:-} ]] || break
 
 			found+=("${try[*]}")
+
+			shift
 		done
 
 		[[ ${#found[@]} -gt 0 ]] || .die "No command found: ${args[*]}"
@@ -855,47 +938,30 @@ if [[ ${OVERSCORE_SOURCE:-} = true ]] || [[ "${BASH_SOURCE[0]}" = "$0" ]]; then
 
 		# Test command succeed
 		test.ok() {
-			case $1 in
-			-msg=*)
-				msg=${1#*=}
-				shift
-				;;
-			esac
+			_[.error]="Command expected to succeed but failed: $*"
 
-			"$@" || .die "${msg:-Command expected to succeed but failed: $@}"
+			"$@"
 		}
-
-		readonly -f test.ok
 
 		# Test command failed
 		test.notok() {
-			case $1 in
-			-msg=*)
-				msg=${1#*=}
-				shift
-				;;
-			esac
+			_[.error]="Command expected to fail but succeeded: $*"
 
-			"$@" && .die "${msg:-Command expected to fail but succeeded: $@}"
+			! "$@"
 		}
-
-		readonly -f test.notok
 
 		# Test actual value equals to expected
 		test.is() {
-			case $1 in
-			-msg=*)
-				msg=${1#*=}
-				shift
-				;;
-			esac
-
 			local expected=$1 actual=$2
 
-			[[ $expected = "$actual" ]] || .die "${msg:-"Expected '$expected' where found '$actual'"}"
+			_[.error]="Expected '$expected' where found '$actual'"
+
+			[[ $expected = "$actual" ]]
 		}
 
-		readonly -f test.is
+		test.end() {
+			:
+		}
 EOF
 		echo
 		echo "OVERSCORE=$(self.path)"
@@ -948,7 +1014,7 @@ EOF
 			fi
 		}
 
-		t() {
+		..t() {
 			if [[ $# -gt 0 ]]; then
 				local name=$1
 				shift
@@ -960,6 +1026,10 @@ EOF
 				"$test" "$@"
 
 				return 0
+			else
+				"$OVERSCORE" "$@"
+
+				return
 			fi
 
 			(
@@ -968,6 +1038,40 @@ EOF
 				.t
 			) || exit 1
 		}
+
+		.load() {
+			local src
+
+			for src; do
+				if [[ -f $src ]]; then
+					builtin source "$src"
+				fi
+			done
+		}
+
+		t() {
+			local -A _=()
+
+			[[ $# -gt 0 ]] || .die 'Test command and message required'
+
+			local test=test.$1
+			shift
+
+			local case=${1:-}
+			shift || true
+
+			if .callable "$test"; then
+				if "$test" "$@"; then
+					"$OVERSCORE" success "$case"
+				else
+					"$OVERSCORE" failure "$case" "${_[.error]}"
+				fi
+			else
+				"$OVERSCORE" "$@"
+			fi
+		}
+
+		.load "$@"
 EOF
 	}
 
