.

diff --git a/bin/t b/bin/t
--- a/bin/t
+++ b/bin/t
@@ -906,7 +906,12 @@ if [[ ${OVERSCORE_SOURCE:-} = true ]] || [[ "${BASH_SOURCE[0]}" = "$0" ]]; then
 		['app.dispatch']='shellcheck disable=2154'
 		['assert.ok']='Assert command succeed'
 		['assert.notok']='Assert command failed'
-		['assert.is']='Assert actual value equals to expected'
+		['assert.is']='Assert actual value equals to the expected'
+		['assert.isnt']='Assert got value not equals to the expected'
+		['assert.like']='Assert got value matches with the expected'
+		['assert.unlike']='Assert got value not matches with the expected'
+		['assert.out']='Assert successful command outputs'
+		['assert.err']='Assert failed command outputs'
 		['t.go']='shellcheck disable=2034'
 		['t']='shellcheck disable=2034'
 	)
@@ -1082,16 +1087,70 @@ if [[ ${OVERSCORE_SOURCE:-} = true ]] || [[ "${BASH_SOURCE[0]}" = "$0" ]]; then
 			! eval -- "$@"
 		}
 
-		# Assert actual value equals to expected
+		# Assert actual value equals to the expected
 		assert.is() {
 			local -n assert_is_=${1?${FUNCNAME[0]}: missing argument}; shift
 
+			local got=${1?${FUNCNAME[0]}: missing argument};      shift
 			local expected=${1?${FUNCNAME[0]}: missing argument}; shift
-			local actual=${1?${FUNCNAME[0]}: missing argument};   shift
 
-			assert_is_="Expected '$expected' where found '$actual'"
+			assert_is_="Got '$got' where expected '$expected'"
 
-			[[ $expected = "$actual" ]]
+			[[ $got = "$expected" ]]
+		}
+
+		# Assert got value not equals to the expected
+		assert.isnt() {
+			local -n assert_isnt_=${1?${FUNCNAME[0]}: missing argument}; shift
+
+			local got=${1?${FUNCNAME[0]}: missing argument};      shift
+			local expected=${1?${FUNCNAME[0]}: missing argument}; shift
+
+			assert_isnt_="Got unexpected '$got'"
+
+			[[ $got != "$expected" ]]
+		}
+
+		# Assert got value matches with the expected
+		assert.like() {
+			local -n assert_like_=${1?${FUNCNAME[0]}: missing argument}; shift
+
+			local got=${1?${FUNCNAME[0]}: missing argument};      shift
+			local expected=${1?${FUNCNAME[0]}: missing argument}; shift
+
+			assert_like_="Got '$got' where expected to match with '$expected'"
+
+			[[ $got =~ $expected ]]
+		}
+
+		# Assert got value not matches with the expected
+		assert.unlike() {
+			local -n assert_unlike_=${1?${FUNCNAME[0]}: missing argument}; shift
+
+			local got=${1?${FUNCNAME[0]}: missing argument};      shift
+			local expected=${1?${FUNCNAME[0]}: missing argument}; shift
+
+			assert_unlike_="Got '$got' where expected to unmatch with '$expected'"
+
+			[[ ! $got =~ $expected ]]
+		}
+
+		# Assert successful command outputs
+		assert.out() {
+			local -n assert_out_=${1?${FUNCNAME[0]}: missing argument}; shift
+
+			local err=0
+
+			eval -- "$@" || err=$?
+		}
+
+		# Assert failed command outputs
+		assert.err() {
+			local -n assert_err_=${1?${FUNCNAME[0]}: missing argument}; shift
+
+			local err=0
+
+			eval -- "$@" || err=$?
 		}
 
 		declare -gr _SELF=$_SELF
