.

diff --git a/bin/underscore b/bin/underscore
--- a/bin/underscore
+++ b/bin/underscore
@@ -2598,68 +2598,61 @@ declare -Ag _command=(
 .builtin() {
 	echo "UNDERSCORE=$(self.path)"
 	echo
-	cat <<'EOF'
-.() {
-	# prelude.sh - Standard prelude
+	sed 's/^\t//' <<'EOF'
+	.() {
+		#:lib/prelude.sh
 
-	[ -n "${BASH_VERSION:-}"        ] || { echo >&2 'Bash required.';                         exit 1; }
-	[[ ${BASH_VERSINFO[0]:-} -ge 4 ]] || { echo >&2 'Bash version 4 or higher required.';     exit 1; }
-	[[ -x /usr/bin/apt-get         ]] || { echo >&2 'Only Debian and derivatives supported.'; exit 1; }
+		declare -grx UNDERSCORE=$UNDERSCORE
 
-	set -Eeuo pipefail; shopt -s nullglob; [[ -z ${TRACE:-} ]] || set -x; unset CDPATH; IFS=$' \t\n'
+		case ${1:-} in
+		-root)
+			[[ ${EUID:-} -eq 0 ]] || { echo >&2 'Root privileges required.'; exit 1; }
+			shift
+			;;
+		esac
 
-	export LC_ALL=C.UTF-8 LANG=C.UTF-8
+		_.die() {
+			"$UNDERSCORE" die "$@"; exit $?
+		}
 
-	declare -grx UNDERSCORE=$UNDERSCORE
+		_.cry() {
+			"$UNDERSCORE" cry "$@"
+		}
 
-	case ${1:-} in
-	-root)
-		[[ ${EUID:-} -eq 0 ]] || { echo >&2 'Root privileges required.'; exit 1; }
-		shift
-		;;
-	esac
+		_.bye() {
+			"$UNDERSCORE" bye "$@"; exit $?
+		}
 
-	_.die() {
-		"$UNDERSCORE" die "$@"; exit $?
+		_.bug() {
+			"$UNDERSCORE" bug "$@"; exit $?
+		}
+
+		_.enter() {
+			local dir
+
+			if dir=$("$UNDERSCORE" enter "$@") && [[ -n $dir ]]; then
+				pushd "$dir" &>/dev/null || exit
+			fi
+		}
+
+		_.leave() {
+			popd &>/dev/null || exit
+		}
+
+		unset -f "${FUNCNAME[0]}"
 	}
 
-	_.cry() {
-		"$UNDERSCORE" cry "$@"
+	_() {
+		local cmd=$1
+
+		case $cmd in
+		die|cry|bye|bug|enter|leave) shift; _."$cmd" "$@" ;;
+		*)                       "$UNDERSCORE" "$@"   ;;
+		esac
 	}
 
-	_.bye() {
-		"$UNDERSCORE" bye "$@"; exit $?
-	}
-
-	_.bug() {
-		"$UNDERSCORE" bug "$@"; exit $?
-	}
-
-	_.enter() {
-		local dir
-
-		if dir=$("$UNDERSCORE" enter "$@") && [[ -n $dir ]]; then
-			pushd "$dir" &>/dev/null || exit
-		fi
-	}
-
-	_.leave() {
-		popd &>/dev/null || exit
-	}
-
-	unset -f "${FUNCNAME[0]}"
-}
-
-_() {
-	local cmd=$1
-
-	case $cmd in
-	die|cry|bye|bug|enter|leave) shift; _."$cmd" "$@" ;;
-	*)                       "$UNDERSCORE" "$@"   ;;
-	esac
-}
-
-. "$@"
+	# shellcheck disable=1090
+	. "$@"
 EOF
 }
 
