.

diff --git a/she b/she
--- a/she
+++ b/she
@@ -181,6 +181,41 @@ expired() {
 # init
 .
 
+# self.sh - Functions related to program itself
+
+# self.version: Print self version
+self.version() {
+	echo 0.0
+}
+
+# self.name: Print self name
+self.name() {
+	echo she
+}
+
+# self.path: Print self path
+self.path() {
+	local self
+
+	self=${BASH_SOURCE[0]}
+	case $self in
+	./*) readlink -f "$self" ;;
+	/*)  echo "$self" ;;
+	*)   readlink -f "$(command -v "$self")" ;;
+	esac
+}
+
+self.usage() {
+	local message
+
+	for message;  do
+		echo >&2 "$message"
+	done
+
+	echo >&2 "Usage: $(self.path) CMD [ARGS]..."
+	exit 1
+}
+
 # flag.sh - Flag handling
 
 flag.parse() {
@@ -340,6 +375,26 @@ string.delete_suffix() {
 	string.has_suffix_deleted "$@" || :
 }
 
+# array.sh - Array functions
+
+# Join array with the given separator
+array.join() {
+	local IFS=$1
+	shift
+
+	echo "$*"
+}
+# Duplicate array
+array.dup() {
+	local -n array_dup_lhs_=$1 array_dup_rhs_=$2
+
+	local key
+	for key in "${!array_dup_rhs_[@]}"; do
+		# shellcheck disable=2034
+		array_dup_lhs_[$key]=${array_dup_rhs_[$key]}
+	done
+}
+
 # path.sh - Path management
 
 path.is_volatile() {
@@ -416,52 +471,6 @@ path.normalize() {
 	while [[ $path_normalize_ =~ //+ ]]; do
 		path_normalize_=${path_normalize_/\/\//\/}
 	done
-}
-
-# https.sh - HTTP functions
-
-# http.get: Get URL
-http.get() {
-	local url=$1
-
-	[[ $url =~ ^.*:// ]] || url=https://$url
-
-	curl -fsSL "$url"
-}
-
-# self.sh - Functions related to program itself
-
-# self.version: Print self version
-self.version() {
-	echo 0.0
-}
-
-# self.name: Print self name
-self.name() {
-	echo she
-}
-
-# self.path: Print self path
-self.path() {
-	local self
-
-	self=${BASH_SOURCE[0]}
-	case $self in
-	./*) readlink -f "$self" ;;
-	/*)  echo "$self" ;;
-	*)   readlink -f "$(command -v "$self")" ;;
-	esac
-}
-
-self.usage() {
-	local message
-
-	for message;  do
-		echo >&2 "$message"
-	done
-
-	echo >&2 "Usage: $(self.path) CMD [ARGS]..."
-	exit 1
 }
 
 # trap.sh - Trap setup
@@ -563,257 +572,6 @@ temp.clean() {
 	local -n temp_clean_=${1?missing 1th argument: name reference}
 
 	[[ -z ${!temp_clean_:-} ]] || rm -f -- "${!temp_clean_}"
-}
-
-# array.sh - Array functions
-
-# Join array with the given separator
-array.join() {
-	local IFS=$1
-	shift
-
-	echo "$*"
-}
-# Duplicate array
-array.dup() {
-	local -n array_dup_lhs_=$1 array_dup_rhs_=$2
-
-	local key
-	for key in "${!array_dup_rhs_[@]}"; do
-		# shellcheck disable=2034
-		array_dup_lhs_[$key]=${array_dup_rhs_[$key]}
-	done
-}
-
-# uel.sh - URL processing
-
-# Parse URL
-# shellcheck disable=2034
-url.parse() {
-	local -n url_parse_=_
-	if [[ ${1:-} = -A ]]; then
-		shift
-		url_parse_=${1?missing 1th argument: hash reference}
-	fi
-
-	local url=${1?missing 1th argument: url}
-
-	# shellcheck disable=1007
-	local proto= userinfo= host= port= path= frag=
-
-	if [[ $url =~ ^(/|./|file://) ]]; then
-		proto='file';  url=${url#*://}
-		tag=${url#*@}; url=${url%@*}
-		path=$url
-
-		# shellcheck disable=2209
-		url_parse_[proto]=file
-		url_parse_[path]=$path
-
-		return 0
-	fi
-
-	if [[ $url =~ ^.+:// ]]; then
-		proto=${url%%://*}; url=${url#*://}
-	fi
-
-	if [[ $url =~ ^[^@/]+@[^/:]+ ]]; then
-		userinfo=${url%%@*}; url=${url#*@}
-	fi
-
-	if [[ $url =~ ^[^:]+:[0-9]+ ]]; then
-		host=${url%%:*};      url=${url#$host:}
-		port=${url%%[^0-9]*}; url=${url#$port}
-	else
-		host=${url%%[/:]*};   url=${url#*[/:]}
-	fi
-
-	if [[ $url =~ ^: ]]; then
-		url=${url#*:}
-
-		if [[ -n $proto ]]; then
-			if [[ $proto != ssh ]]; then
-				# shellcheck disable=2154
-				url_parse_[error]='protocol mismatch'
-				return 1
-			fi
-		else
-			proto=ssh
-		fi
-	else
-		url=${url#/}
-
-		if [[ -n $proto && $proto = ssh ]]; then
-			url_parse_[error]='invalid SSH url'
-			return 1
-		fi
-	fi
-
-	if [[ -z $proto ]]; then
-		proto=https
-	fi
-
-	if [[ $url =~ [#].*$ ]]; then
-		frag=${url#*#}; url=${url%#*}
-	fi
-
-	path=$url
-
-	url_parse_[frag]=$frag
-	url_parse_[host]=$host
-	url_parse_[path]=$path
-	url_parse_[port]=$port
-	url_parse_[proto]=$proto
-	url_parse_[userinfo]=$userinfo
-}
-
-# url.dump: TODO
-url.dump() {
-	url.parse "$1"
-	hmm _
-}
-
-# git.sh - Git functions
-
-git.is_git() {
-	local path=${1:-.}
-
-	[[ -d $path/.git ]] && git rev-parse --resolve-git-dir "$path/.git" &>/dev/null
-}
-
-git.must_sane() {
-	git rev-parse --is-inside-work-tree &>/dev/null || die "Must be inside a git work tree: $PWD"
-	git rev-parse --verify HEAD >/dev/null          || die "Unverified git HEAD: $PWD"
-}
-
-git.is_clean() {
-	git rev-parse --verify HEAD >/dev/null &&
-	git update-index -q --ignore-submodules --refresh &&
-	git diff-files --quiet --ignore-submodules &&
-	git diff-index --cached --quiet --ignore-submodules HEAD --
-}
-
-git.must_clean() {
-	git.is_clean || die "Must be a clean git work tree: $PWD"
-}
-
-git.topdir() {
-	local dir
-
-	dir=$(git rev-parse --git-dir) && dir=$(cd "$dir" && pwd)/ && echo "${dir%%/.git/*}"
-}
-
-git.top() {
-	git.must_sane
-
-	must cd "$(git.topdir)"
-}
-
-git.default_branch() {
-	git.must_sane
-
-	git symbolic-ref refs/remotes/origin/HEAD | sed 's@^refs/remotes/origin/@@'
-}
-
-git.switch() {
-	local branch=${1:-}
-
-	[[ -n $branch ]] || branch=$(git.default_branch)
-
-	git checkout --quiet "$branch"
-}
-
-git.update() {
-	local -A _=(
-		[-expiry]=3
-	)
-
-	flag.parse "$@"
-
-	if expired "${_[-expiry]}" .git/FETCH_HEAD; then
-		git.must_clean
-		git pull --quiet origin
-	fi
-}
-
-git.dst_() {
-	file.dst_ "$@"
-}
-
-git.exist_() {
-	local dst=${1?missing 1st argumenet: dst}
-
-	git.dst_ dst
-
-	[[ -d $dst ]]
-}
-
-git.enter_() {
-	local dst=${1?missing 1st argument: dst}
-
-	git.dst_ dst
-
-	[[ -d $dst ]] || die "Destination not found: $dst"
-
-	must pushd "$dst" >/dev/null
-
-	git.is_git . || die "Not a git repository: $PWD"
-
-	file.enter "${_[dir]:-}"
-}
-
-git.clone_() {
-	local url=${1?missing 1th argument: url}
-	local dst=${2?missing 2nd argument: dst}
-
-	! git.exist_ "$dst" || die "Destination already exist: $dst"
-
-	local -a opt
-
-	[[ -z ${_[-shallow]:-} ]] || opt+=(--depth 1)
-	[[ -z ${_[branch]:-}   ]] || opt+=(--branch "${_[branch]}")
-
-	_func_() {
-		git clone "${opt[@]}" "$url" .
-		file.do_ copy . "$dst"
-	}
-
-	temp.inside _func_
-
-	unset -f _func_
-}
-
-git.update_() {
-	local dst=${1?missing 1st argument: dst}
-
-	git.enter_ "$dst"
-
-	git.switch "${_[branch]:-}"
-
-	if expired "${_[-expiry]:-3}" .git/FETCH_HEAD; then
-		git.must_clean
-
-		cry 'Updating repository...'
-		git pull --quiet origin
-	fi
-
-	must popd >/dev/null
-}
-
-# deb.sh - Debian package management
-
-export DEBIAN_FRONTEND=noninteractive APT_KEY_DONT_WARN_ON_DANGEROUS_USAGE=DontWarn
-
-# deb.update: Update Debian package index
-deb.update() {
-	expired 60 /var/cache/apt/pkgcache.bin || apt-get update
-}
-
-# deb.install: Install Debian packages
-deb.install() {
-	deb.update
-
-	[[ $# -eq 0 ]] || apt-get -y install --no-install-recommends "$@"
 }
 
 # file.sh - File related operations
@@ -974,6 +732,105 @@ file._chogm_() {
 	[[ -z ${_[-mode]:-}  ]] || must chmod "${_[-mode]}"  "$dst"
 	[[ -z ${_[-owner]:-} ]] || must chown "${_[-owner]}" "$dst"
 	[[ -z ${_[-group]:-} ]] || must chgrp "${_[-group]}" "$dst"
+}
+
+# uel.sh - URL processing
+
+# Parse URL
+# shellcheck disable=2034
+url.parse() {
+	local -n url_parse_=_
+	if [[ ${1:-} = -A ]]; then
+		shift
+		url_parse_=${1?missing 1th argument: hash reference}
+	fi
+
+	local url=${1?missing 1th argument: url}
+
+	# shellcheck disable=1007
+	local proto= userinfo= host= port= path= frag=
+
+	if [[ $url =~ ^(/|./|file://) ]]; then
+		proto='file';  url=${url#*://}
+		tag=${url#*@}; url=${url%@*}
+		path=$url
+
+		# shellcheck disable=2209
+		url_parse_[proto]=file
+		url_parse_[path]=$path
+
+		return 0
+	fi
+
+	if [[ $url =~ ^.+:// ]]; then
+		proto=${url%%://*}; url=${url#*://}
+	fi
+
+	if [[ $url =~ ^[^@/]+@[^/:]+ ]]; then
+		userinfo=${url%%@*}; url=${url#*@}
+	fi
+
+	if [[ $url =~ ^[^:]+:[0-9]+ ]]; then
+		host=${url%%:*};      url=${url#$host:}
+		port=${url%%[^0-9]*}; url=${url#$port}
+	else
+		host=${url%%[/:]*};   url=${url#*[/:]}
+	fi
+
+	if [[ $url =~ ^: ]]; then
+		url=${url#*:}
+
+		if [[ -n $proto ]]; then
+			if [[ $proto != ssh ]]; then
+				# shellcheck disable=2154
+				url_parse_[error]='protocol mismatch'
+				return 1
+			fi
+		else
+			proto=ssh
+		fi
+	else
+		url=${url#/}
+
+		if [[ -n $proto && $proto = ssh ]]; then
+			url_parse_[error]='invalid SSH url'
+			return 1
+		fi
+	fi
+
+	if [[ -z $proto ]]; then
+		proto=https
+	fi
+
+	if [[ $url =~ [#].*$ ]]; then
+		frag=${url#*#}; url=${url%#*}
+	fi
+
+	path=$url
+
+	url_parse_[frag]=$frag
+	url_parse_[host]=$host
+	url_parse_[path]=$path
+	url_parse_[port]=$port
+	url_parse_[proto]=$proto
+	url_parse_[userinfo]=$userinfo
+}
+
+# url.dump: TODO
+url.dump() {
+	url.parse "$1"
+	hmm _
+}
+
+# https.sh - HTTP functions
+
+# http.get: Get URL
+http.get() {
+	local url=$1
+
+	[[ $url =~ ^.*:// ]] || url=https://$url
+
+	curl -fsSL "$url"
 }
 
 # bin.sh - Executable files
@@ -1230,6 +1087,22 @@ src.enter_() {
 	git.enter_ "$@"
 }
 
+# deb.sh - Debian package management
+
+export DEBIAN_FRONTEND=noninteractive APT_KEY_DONT_WARN_ON_DANGEROUS_USAGE=DontWarn
+
+# deb.update: Update Debian package index
+deb.update() {
+	expired 60 /var/cache/apt/pkgcache.bin || apt-get update
+}
+
+# deb.install: Install Debian packages
+deb.install() {
+	deb.update
+
+	[[ $# -eq 0 ]] || apt-get -y install --no-install-recommends "$@"
+}
+
 # is.sh - System predications
 
 # is.virtual: Detect given virtualization
@@ -1287,18 +1160,18 @@ declare -Ag help=(
 	['die']='Print error messages and exit failure'
 	['bug']='Report bug and exit failure'
 	['bye']='Print messages and exit successfully'
-	['http get']='Get URL'
 	['self version']='Print self version'
 	['self name']='Print self name'
 	['self path']='Print self path'
 	['temp inside']='Execute command in temp dir and (optionally) move it elsewhere'
-	['url dump']='TODO'
-	['deb update']='Update Debian package index'
-	['deb install']='Install Debian packages'
 	['file install']='Install file from URL'
+	['url dump']='TODO'
+	['http get']='Get URL'
 	['src install']='Install to a known location'
 	['src use']='Install src into the runtime tree'
 	['enter']='Get src from URL and enter to the directory'
+	['deb update']='Update Debian package index'
+	['deb install']='Install Debian packages'
 	['is virtual']='Detect given virtualization'
 	['is debian']='Detect Debian or its given release'
 	['is ubuntu']='Detect Ubuntu or its given release'
@@ -1336,18 +1209,18 @@ declare -Ag command=(
 	['die']='die'
 	['bug']='bug'
 	['bye']='bye'
-	['http get']='http.get'
 	['self version']='self.version'
 	['self name']='self.name'
 	['self path']='self.path'
 	['temp inside']='temp.inside'
-	['url dump']='url.dump'
-	['deb update']='deb.update'
-	['deb install']='deb.install'
 	['file install']='file.install'
+	['url dump']='url.dump'
+	['http get']='http.get'
 	['src install']='src.install'
 	['src use']='src.use'
 	['enter']='src.enter'
+	['deb update']='deb.update'
+	['deb install']='deb.install'
 	['is virtual']='is.virtual'
 	['is debian']='is.debian'
 	['is ubuntu']='is.ubuntu'
