.

diff --git a/she b/she
--- a/she
+++ b/she
@@ -84,6 +84,20 @@ bool() {
 	esac
 }
 
+included() {
+	local needle=${1?missing argument: needle}
+	shift
+
+	local element
+	for element; do
+		if [[ $element = "$needle" ]]; then
+			return 0
+		fi
+	done
+
+	return 1
+}
+
 # Command must success
 must() {
 	"$@" || die "Command failed: $*"
@@ -405,13 +419,21 @@ array.join() {
 }
 # Duplicate array
 array.dup() {
-	local -n array_dup_lhs_=$1 array_dup_rhs_=$2
+	local -n array_dup_lhs_=${1?missing argument: array reference} array_dup_rhs_=${2?missing argument: array reference}
 
 	local key
 	for key in "${!array_dup_rhs_[@]}"; do
 		# shellcheck disable=2034
 		array_dup_lhs_[$key]=${array_dup_rhs_[$key]}
 	done
+}
+
+# The element included in the given array
+array.included() {
+	local -n array_included_=${1?missing argument: array reference}
+	local element=${2?missing argument: element}
+
+	included "$element" "${array_included_[@]}"
 }
 
 # path.sh - Path management
@@ -709,6 +731,19 @@ file.enter() {
 		[[ -d $dir ]] || die "No path found to enter: $dir"
 		must cd "$dir"
 	fi
+}
+
+file.download() {
+	local url=${1?missing 1th argument: url}
+	local -n file_download_dst_=${2?missing 2nd argument: name reference}
+
+	local tempfile
+
+	temp.file tempfile
+	must http.get "$url" >"$tempfile"
+
+	# shellcheck disable=2034
+	file_download_dst_=$tempfile
 }
 
 # file.sh - Private functions
@@ -1261,47 +1296,98 @@ deb.install() {
 	local -A _=(
 		[-prefer]=
 		[-missings]=false
+		[-clean]=false
+	)
+
+	local -a opts=(
+		--yes
+		--no-install-recommends
 	)
 
 	flag.parse "$@"
-	flag.must 1
 
-	local prefer=${_[-prefer]:-}
+	local prefer=${_[-prefer]:-} target
 
 	case $prefer in
 	backports)
-		local codename
-		codename=$(which.debian codename)
+		local dist; dist=$(which.debian codename)-backports
 
-		if deb.has_backports "$codename"; then
-			deb.repository backports <<-EOF
-				deb http://ftp.debian.org/debian $codename-backports main contrib non-free
+		if is.debian stable && deb._dist_valid "$dist"; then
+			deb._dist_added "$dist" || deb.repository "$dist" <<-EOF
+				deb http://ftp.debian.org/debian $dist main contrib non-free
 			EOF
+			target=$dist
 		fi
 		;;
 	experimental)
+		local dist=experimental
+
 		if is.debian unstable; then
-			deb.repository experimental <<-EOF
-				deb http://ftp.debian.org/debian experimental main contrib non-free
+			deb._dist_added "$dist" || deb.repository experimental <<-EOF
+				deb http://ftp.debian.org/debian $dist main contrib non-free
 			EOF
+			target=$dist
 		fi
 		;;
 	*)
 		die "Unrecognized prefered repository: $prefer"
 	esac
 
+	[[ -z ${target:-} ]] || opts+=(
+		--target-release
+		"$target"
+	)
+
+	local -a packages
+
+	if flag.true missings; then
+		deb._missings packages "$@"
+	else
+		packages=("$@")
+	fi
+
+	[[ ${#packages[@]} -gt 0 ]] || return 0
+
 	deb.update
+	apt-get install "${opts[@]}" "${packages[@]}"
+}
 
-	local -a packages=("$@")
+deb.uninstall() {
+	local -a packages
 
-	flag.false missings || deb.missings packages "$@"
+	deb._missings packages "$@"
+	[[ ${#packages[@]} -gt 0 ]] || return 0
 
-	apt-get -y install --no-install-recommends "${packages[@]}"
+	apt-get purge -y "${packages[@]}"
+
+	might apt-get autoremove -y && might apt-get autoclean -y
+}
+
+deb.install_file() {
+	local url
+	for url; do
+		local deb
+
+		file.download "$url" deb
+		dpkg -i -- "$deb" 2>/dev/null || true
+		apt-get -y install --no-install-recommends --fix-broken
+		rm -f -- "$deb"
+	done
+}
+
+# deb.missings: Print missing packages among given packages
+deb.missings() {
+	local -a missings
+	deb._missings missings "$@"
+
+	for package in "${missings[@]}"; do
+		echo "$package"
+	done
 }
 
 # deb.update: Update Debian package index
 deb.update() {
-	expired 60 /var/cache/apt/pkgcache.bin || apt-get update
+	expired 60 /var/cache/apt/pkgcache.bin || apt-get update -y
 }
 
 # deb.repository: Add Debian repository
@@ -1309,25 +1395,69 @@ deb.repository() {
 	local name=${1?missing argument: name}
 	shift
 
-	local keyurl=${1?missing argument: keyurl}
+	local url=${1?missing argument: url}
 	shift
 
-	has.stdin || bug "No stdin data found"
+	has.stdin || die 'Required stdin data'
 
-	cat >/etc/apt/sources.list.d/"$name".list
-	[[ -z ${keyurl:-} ]] || http.get "$keyurl" | apt-key add -
-
-	apt-get update -y
+	if ! deb._apt_key_add "$url"; then
+		cat >/etc/apt/sources.list.d/"$name".list
+		apt-get update -y
+	fi
 }
 
-deb.missings() {
-	:
+deb._dist_valid() {
+	local dist=${1?missing argument: dist}
+
+	http.ok http://ftp.debian.org/debian/dists/"$dist"/
 }
 
-deb.has_backports() {
-	local codename=${1?missing argument: codename}
+deb._dist_added() {
+	local dist=${1?missing argument: dist}
 
-	http.ok "http://ftp.debian.org/debian/dists/$codename-backports/"
+	grep -qE "^deb.*\bdebian.org\b.*\b$dist\b" /etc/apt/*.list /etc/apt/sources.list.d/*.list
+}
+
+deb._apt_key_add() {
+	local url=${1?missing argument: url}
+
+	local tempfile
+	temp.file tempfile
+
+	http.get "$url" >"$tempfile" || die "Couldn't get key file: $url"
+
+	local -a questioned_fingerprints installed_fingerprints
+
+	mapfile -t questioned_fingerprints < <(
+		gpg -nq --import --import-options import-show --with-colons "$tempfile" | awk -F: '$1 == "fpr" { print $10 }' 2>/dev/null
+	)
+
+	# shellcheck disable=2034
+	mapfile -t installed_fingerprints < <(
+		apt-key adv --list-public-keys --with-fingerprint --with-colon | awk -F: '$1 == "fpr" { print $10 }' 2>/dev/null
+	)
+
+	local fingerprint
+	for fingerprint in "${questioned_fingerprints[@]}"; do
+		included "$fingerprint" "${installed_fingerprints[@]}" || return 1
+	done
+
+	apt-key add "$tempfile"
+
+	rm -f -- "$tempfile"
+}
+
+deb._missings() {
+	local -a deb_missings_=${1?missing argument: array reference}
+	shift
+
+	local package
+	for package in "${[@]}"; do
+		# shellcheck disable=2016
+		if [ -z "$(dpkg-query -W -f='${Installed-Size}' "$package" 2>/dev/null ||:)" ]; then
+			deb_missings_+=("$package")
+		fi
+	done
 }
 
 # is.sh - System predications
@@ -1408,6 +1538,7 @@ declare -Ag help=(
 	['enter']='Get src from URL and enter to the directory'
 	['run']='Run src from URL'
 	['deb install']='Install Debian packages'
+	['deb missings']='Print missing packages among given packages'
 	['deb update']='Update Debian package index'
 	['deb repository']='Add Debian repository'
 	['is virtual']='Detect given virtualization'
@@ -1458,6 +1589,7 @@ declare -Ag command=(
 	['enter']='src.enter'
 	['run']='src.run'
 	['deb install']='deb.install'
+	['deb missings']='deb.missings'
 	['deb update']='deb.update'
 	['deb repository']='deb.repository'
 	['is virtual']='is.virtual'
