.

diff --git a/she b/she
--- a/she
+++ b/she
@@ -12,94 +12,92 @@ export LC_ALL=C.UTF-8 LANG=C.UTF-8
 
 # kernel.sh - Core functions
 
-# say: Print messages on standard error
 say() {
-	local message
+	if [[ $# -eq 0 ]]; then
+		echo >&2 ""
+	else
+		local message
 
-	for message; do
-		echo -e >&2 "$message"
-	done
+		for message; do
+			echo -e >&2 "$message"
+		done
+	fi
 }
 
-# cry: Print warning messages on standard error
 cry() {
 	if [[ $# -eq 0 ]]; then
 		echo >&2 ""
+	else
+		local message
 
-		return
+		for message; do
+			echo -e >&2 "W: $message"
+		done
 	fi
-
-	echo >&2 "W: $1"
-	shift
-
-	while [[ $# -gt 0 ]]; do
-		echo >&2 "$1"
-		shift
-	done
 }
 
-# die: Print error messages and exit failure
+die-() {
+	if [[ $# -eq 0 ]]; then
+		echo >&2 ""
+	else
+		local message
+
+		for message; do
+			echo -e >&2 "E: $message"
+		done
+	fi
+}
+
 die() {
-	if [[ $# -eq 0 ]]; then
-		echo >&2 ""
+	die- "$@"
 
-		return
-	fi
-
-	echo >&2 "E: $1"
-	shift
-
-	while [[ $# -gt 0 ]]; do
-		echo >&2 "$1"
-		shift
-	done
-
-        exit 1
+	exit 1
 }
 
-# bug: Report bug and exit failure
+bug-() {
+	if [[ $# -eq 0 ]]; then
+		echo >&2 ""
+	else
+		local message
+
+		for message; do
+			echo -e >&2 "B: $message"
+		done
+	fi
+}
+
 bug() {
-	if [[ $# -eq 0 ]]; then
-		echo >&2 ""
+	bug- "$@"
 
-		return
-	fi
-
-	echo >&2 "B: $1"
-	shift
-
-	while [[ $# -gt 0 ]]; do
-		echo >&2 "$1"
-		shift
-	done
-
-        exit 127
+	exit 127
 }
 
-# bye: Print messages and exit successfully
 bye() {
-	local message
+	if [[ $# -eq 0 ]]; then
+		echo >&2 ""
+	else
+		local message
 
-	for message; do
-		echo -e >&2 "$message"
-	done
+		for message; do
+			echo -e >&2 "B: $message"
+		done
+	fi
 
 	exit 0
 }
 
-# hey: Print colored messages
 hey() {
-	local message=$1
-	shift
+	if [[ $# -eq 0 ]]; then
+		echo >&2 ""
+	else
+		local message
 
-	echo -e >&2 "\\e[38;5;14m-->\\e[0m\\e[1m $message\\e[0m"
-
-	for message; do
-		echo -e >&2 "    $message"
-	done
+		for message; do
+			echo -e >&2 "\\e[38;5;14m-->\\e[0m\\e[1m $message\\e[0m"
+		done
+	fi
 }
 
-# Dump an array variable
 hmm() {
 	while [[ $# -gt 0 ]]; do
 		# shellcheck disable=2178,2155
@@ -165,7 +163,6 @@ included() {
 	return 1
 }
 
-# Check timestamp of reference files against given expiry in minutes
 expired() {
 	local -i expiry=${1?${FUNCNAME[0]}: missing argument}; shift
 
@@ -186,7 +183,7 @@ expired() {
 # shellcheck disable=2034
 .() {
 	# Program name
-	readonly PROGNAME=${0##*/}
+	declare -ag PROGNAME=("${0##*/}")
 
 	# Core environment
 	if [[ ${EUID:-} -eq 0 ]]; then
@@ -281,6 +278,235 @@ _.reset() {
 
 _.dump() {
 	hmm _
+}
+
+# flag.sh - Flag handling
+
+shopt -s expand_aliases
+
+# shellcheck disable=2142
+alias flag.parse='flag.parse_ "$@"; local -a __a; flag.args_ __a; set -- "${__a[@]}"; unset -v __a'
+
+flag.parse_() {
+	local -A flag_parse_
+
+	_.reset flag_parse_
+
+	local -i i=0
+
+	while [[ $# -gt 0 ]]; do
+		local key value
+
+		if [[ $1 = -help ]]; then
+			flag.usage_ flag_parse_
+			exit 0
+		elif [[ $1 =~ ^-*[[:alpha:]_][[:alnum:]_]*= ]]; then
+			key=${1%%=*}; value=${1#*=}
+			if [[ $key =~ ^-.+$ ]] && [[ ! -v flag_parse_[$key] ]]; then
+				die "Unrecognized flag: $key"
+			fi
+		elif [[ $1 == '--' ]]; then
+			shift
+			break
+		else
+			key=$((++i)); value=$1
+		fi
+
+		_["$key"]=${value:-${_["$key"]:-}}
+
+		shift
+	done
+
+	flag._post flag_parse_ "$i"
+}
+
+flag.usage_() {
+	local -n flag_usage_=${1:-_}
+
+	say "Usage: ${PROGNAME[*]} ${flag_usage_[.help]:-}"
+}
+
+flag.args_() {
+	_.values '^[1-9][0-9]*$' "$@"
+}
+
+flag.env_() {
+	_.values '^[[:alpha:]_][[:alnum:]_]*$' "$@"
+}
+
+flag.true() {
+	bool "${_[-$1]:-}"
+}
+
+flag.false() {
+	! flag.true "$@"
+}
+
+flag.dump() {
+	_.dump
+}
+
+flag._post() {
+	local -n flag_post_=${1?missing argument}; shift
+	local    i=${1?missing argument};          shift
+
+	local argc=${flag_post_[.argc]:-0}
+
+	[[ $argc != '-' ]] || return 0
+
+	local lo hi
+
+	if [[ $argc =~ ^[0*9]+$ ]]; then
+		lo=$argc; hi=$argc
+	elif [[ $argc =~ ^[0-9]*-[0-9]*$ ]]; then
+		IFS=- read -r lo hi <<<"$argc"
+	else
+		bug "Incorrect range: $argc"
+	fi
+
+	if   [[ -n ${lo:-} ]] && [[ $i -lt $lo ]]; then
+		die- 'Too few arguments'
+	elif [[ -n ${hi:-} ]] && [[ $i -gt $hi ]]; then
+		die- 'Too many arguments'
+	else
+		return 0
+	fi
+
+	die-
+	flag.usage_ flag_post_
+	exit 1
+}
+
+flag._help() {
+	local -n flag_help_=${1?missing argument}; shift
+
+	if [[ -n ${flag_help_[.help]:-} ]]; then
+		# shellcheck disable=2128
+		echo "Usage: ${PROGNAME[*]} ${flag_help_[.help]}"
+	else
+		# shellcheck disable=2128
+		echo "Usage: ${PROGNAME[*]}"
+	fi
+}
+
+# help: Display help
+help() {
+	local -A _=(
+		[.help]='COMMAND...'
+		[.argc]=0-
+	)
+
+	flag.parse
+
+	.help "$@"
+}
+
+# ui.sh - UI functions
+
+# say: Print messages on standard error
+ui.say() {
+	local -A _=(
+		[.help]='[MESSAGE...]'
+		[.argc]=0-
+	)
+
+	flag.parse
+
+	ui._plain "$@"
+}
+
+# die: Print error messages and exit failure
+ui.die() {
+	local -A _=(
+		[-unexit]=false
+		[.help]='[-unexit=BOOL [MESSAGE...]]'
+		[.argc]=0-
+	)
+
+	flag.parse
+
+	ui._error "$@"
+
+	flag.true unexit || exit 1
+}
+
+# cry: Print warning messages on standard error
+ui.cry() {
+	local -A _=(
+		[.help]='[MESSAGE...]'
+		[.argc]=0-
+	)
+
+	flag.parse
+
+	ui._warning "$@"
+}
+
+# bug: Report bug and exit failure
+ui.bug() {
+	local -A _=(
+		[-unexit]=false
+		[.help]='[-unexit=BOOL [MESSAGE...]]'
+		[.argc]=0-
+	)
+
+	flag.parse
+
+	ui._bug "$@"
+
+	flag.true unexit || exit 127
+}
+
+# hey: Print messages taking attention
+ui.hey() {
+	local -A _=(
+		[.help]='[MESSAGE...]'
+		[.argc]=0-
+	)
+
+	flag.parse
+
+	ui._hey "$@"
+}
+
+ui._plain() {
+	local message
+
+	for message; do
+		echo -e >&2 "$message"
+	done
+}
+
+ui._error() {
+	local message
+
+	for message; do
+		echo -e >&2 "E: $message"
+	done
+}
+
+ui._warning() {
+	local message
+
+	for message; do
+		echo -e >&2 "W: $message"
+	done
+}
+
+ui._bug() {
+	local message
+
+	for message; do
+		echo -e >&2 "B: $message"
+	done
+}
+
+ui._hey() {
+	local message
+
+	for message; do
+		echo -e >&2 "\\e[38;5;14m-->\\e[0m\\e[1m $message\\e[0m"
+	done
 }
 
 # must.sh - Guard functions
@@ -422,6 +648,7 @@ self.version() {
 self.name() {
 	local -A _; flag.parse
 
+	# shellcheck disable=2128
 	echo "$PROGNAME"
 }
 
@@ -442,7 +669,7 @@ self.path() {
 
 # self.install: Install self
 self.install() {
-	# shellcheck disable=2192
+	# shellcheck disable=2192,2128
 	local -A _=(
 		[-prefix]="$_USR"/bin
 		[-name]=$PROGNAME
@@ -456,113 +683,6 @@ self.install() {
 	_[1]=$(self.path)
 
 	bin.install_
-}
-
-self.usage() {
-	local -A _; flag.parse
-
-	local message
-
-	for message;  do
-		echo >&2 "$message"
-	done
-
-	echo >&2 "Usage: $(self.path) CMD [ARGS]..."
-	exit 1
-}
-
-# flag.sh - Flag handling
-
-shopt -s expand_aliases
-
-# shellcheck disable=2142
-alias flag.parse='flag.parse_ "$@"; set -- $(flag.args_)'
-
-flag.parse_() {
-	local -A flag_parse_
-
-	_.reset flag_parse_
-
-	local -i i=0
-
-	while [[ $# -gt 0 ]]; do
-		local key value
-
-		if [[ $1 =~ ^-*[[:alpha:]_][[:alnum:]_]*= ]]; then
-			key=${1%%=*}; value=${1#*=}
-			if [[ $key =~ ^-.+$ ]] && [[ ! -v flag_parse_[$key] ]]; then
-				die "Unrecognized flag: $key"
-			fi
-		elif [[ $1 == '--' ]]; then
-			shift
-			break
-		else
-			key=$((++i)); value=$1
-		fi
-
-		_["$key"]=${value:-${_["$key"]:-}}
-
-		shift
-	done
-
-	flag._post flag_parse_ "$i"
-}
-
-flag.args_() {
-	_.values '^[1-9][0-9]*$' "$@"
-}
-
-flag.env_() {
-	_.values '^[[:alpha:]_][[:alnum:]_]*$' "$@"
-}
-
-flag.true() {
-	bool "${_[-$1]:-}"
-}
-
-flag.false() {
-	! flag.true "$@"
-}
-
-flag.dump() {
-	_.dump
-}
-
-flag._post() {
-	local -n flag_post_=${1?missing argument}; shift
-	local    i=${1?missing argument};          shift
-
-	local argc=${flag_post_[.argc]:-0}
-
-	[[ $argc = '-' ]] || return 0
-
-	local lo hi
-
-	if [[ $argc =~ ^[0*9]+$ ]]; then
-		lo=$argc; hi=$argc
-	elif [[ $argc =~ ^[0-9]*-[0-9]*$ ]]; then
-		IFS=- read -r lo hi <<<"$argc"
-	else
-		bug "Incorrect range: $argc"
-	fi
-
-	local -a messages
-
-	if   [[ -n ${lo:-} ]] && [[ $i -lt $lo ]]; then
-		messages+=('Too few arguments')
-	elif [[ -n ${hi:-} ]] && [[ $i -gt $hi ]]; then
-		messages+=('Too many arguments')
-	else
-		return 0
-	fi
-
-	if [[ -n ${flag_post_[.help]:-} ]]; then
-		messages+=("" "Usage: ${COMMAND:-} ${flag_post_[.help]}")
-	else
-		messages+=("" "Usage: ${COMMAND:-}")
-	fi
-
-	die "${messages[@]}"
 }
 
 # string.sh - String manipulation
@@ -829,6 +949,7 @@ temp.file() {
 
 	local file
 
+	# shellcheck disable=2128
 	file=$(mktemp -p "${TMPDIR:-/tmp}" "$PROGNAME".XXXXXXXX) || die 'Fatal error: mktemp'
 	at_exit_files "$file"
 
@@ -841,6 +962,8 @@ temp.dir() {
 	local -n temp_dir_=${1?${FUNCNAME[0]}: missing argument}; shift
 
 	local dir
+
+	# shellcheck disable=2128
 	dir=$(mktemp -p "${TMPDIR:-/tmp}" -d "$PROGNAME".XXXXXXXX) || die 'Fatal error: mktemp'
 	at_exit_files "$dir"
 
@@ -902,7 +1025,7 @@ os.codename() {
 # os.is: Detect OS feature
 os.is() {
 	local -A _=(
-		[.help]='feature'
+		[.help]='FEATURE'
 		[.argc]=1-
 	)
 
@@ -978,7 +1101,7 @@ os.is._physical() {
 # url.is: Assert URL feature
 url.is() {
 	local -A _=(
-		[.help]='local|(proto|host|port|path|userinfo|frag) value'
+		[.help]='local|(proto|host|port|path|userinfo|frag) VALUE'
 		[.argc]=2-
 	)
 
@@ -1090,7 +1213,7 @@ url.is_() {
 # http.get: Get URL
 http.get() {
 	local -A _=(
-		[.help]='url'
+		[.help]='URL'
 		[.argc]=1
 	)
 
@@ -1106,7 +1229,7 @@ http.get() {
 # http.is: Assert URL response
 http.is() {
 	local -A _=(
-		[.help]='url code'
+		[.help]='URL CODE'
 		[.argc]=2
 	)
 
@@ -1135,7 +1258,7 @@ file.install() {
 		[-owner]=
 		[-prefix]=
 
-		[.help]='[-(group|mode|owner|prefix)=value] url [dst]'
+		[.help]='[-(group|mode|owner|prefix)=VALUE] URL [FILE]'
 		[.argc]=1
 	)
 
@@ -1168,7 +1291,7 @@ file.chogm() {
 		[-mode]=
 		[-owner]=
 
-		[.help]='[-(group|mode|owner)=value] dst'
+		[.help]='[-(group|mode|owner)=VALUE] URL [FILE]'
 		[.argc]=1
 	)
 
@@ -1290,7 +1413,7 @@ file._do_args_() {
 		[-owner]=
 		[-prefix]=
 
-		[.help]='[-(group|mode|owner|prefix)=value] src [dst]'
+		[.help]='[-(GROUP|MODE|OWNER|PREFIX)=VALUE] SRC [DST]'
 		[.argc]=1
 	)
 
@@ -1318,7 +1441,7 @@ bin.install() {
 		[-prefix]="$_USR"/bin
 		[-name]=
 
-		[.help]='url|file'
+		[.help]='URL|FILE'
 		[.argc]=1
 	)
 
@@ -1334,7 +1457,7 @@ bin.use() {
 		[-prefix]="$_RUN"/bin
 		[-name]=
 
-		[.help]='url|file'
+		[.help]='URL|FILE'
 		[.argc]=1
 	)
 
@@ -1407,7 +1530,7 @@ git.update() {
 	local -A _=(
 		[-expiry]=3
 
-		[.help]='[-expiry=value (minutes)]'
+		[.help]='[-expiry=MINUTES]'
 		[.argc]=0
 	)
 
@@ -1543,7 +1666,7 @@ src.install() {
 		[-expiry]=
 		[-prefix]="$_USR"/src
 
-		[.help]='[-(expiry|prefix)=value] url'
+		[.help]='[-(expiry=MINUTES|prefix=DIR)] URL'
 		[.argc]=1
 	)
 
@@ -1560,7 +1683,7 @@ src.use() {
 		[-prefix]="$_RUN"/src
 		[-shallow]=false
 
-		[.help]='[-(expiry|prefix|shallow)=value] url'
+		[.help]='[-(expiry=MINUTES|prefix=DIR|shallow=BOOL)] URL'
 		[.argc]=1
 	)
 
@@ -1577,7 +1700,7 @@ src.enter() {
 		[-prefix]="$_RUN"/src
 		[-shallow]=false
 
-		[.help]='[-(expiry|prefix|shallow)=value] url'
+		[.help]='[-(expiry=MINUTES|prefix=DIR|shallow=BOOL)] URL'
 		[.argc]=1
 	)
 
@@ -1598,7 +1721,7 @@ src.run() {
 		[-shallow]=false
 		[-test]=false
 
-		[.help]='[-(expiry|prefix|pwd|shallow|test)=value] url'
+		[.help]='[-(expiry=MINUTES|prefix=DIR|pwd=DIR|shallow=BOOL|test=BOOL)] url'
 		[.argc]=1
 	)
 
@@ -1781,7 +1904,7 @@ deb.install() {
 		[-missings]=false
 		[-shiny]=false
 
-		[.help]='package...'
+		[.help]='PACKAGE...'
 	)
 
 	flag.parse
@@ -1839,7 +1962,7 @@ deb.install() {
 deb.uninstall() {
 	# shellcheck disable=2192
 	local -A _=(
-		[.help]='package...'
+		[.help]='PACKAGE...'
 	)
 
 	flag.parse
@@ -1858,7 +1981,7 @@ deb.uninstall() {
 deb.missings() {
 	# shellcheck disable=2192
 	local -A _=(
-		[.help]='package...'
+		[.help]='PACKAGE...'
 	)
 
 	flag.parse
@@ -1889,7 +2012,7 @@ deb.update() {
 deb.repository() {
 	# shellcheck disable=2192
 	local -A _=(
-		[.help]='name [url]'
+		[.help]='NAME [URL]'
 		[.argc]=1-
 	)
 
@@ -1911,7 +2034,7 @@ deb.repository() {
 deb.using() {
 	# shellcheck disable=2192
 	local -A _=(
-		[.help]='dist...'
+		[.help]='DIST...'
 		[.argc]=1-
 	)
 
@@ -2009,7 +2132,7 @@ deb._install_from_urls() {
 # text.fix: Append stdin content to the target file
 text.fix() {
 	local -A _=(
-		[.help]='file'
+		[.help]='FILE'
 		[.argc]=1
 	)
 
@@ -2029,7 +2152,7 @@ text.fix() {
 # text.unfix: Remove appended content
 text.unfix() {
 	local -A _=(
-		[.help]='file'
+		[.help]='FILE'
 		[.argc]=1
 	)
 
@@ -2057,7 +2180,7 @@ filetype.mime() {
 	local -A _=(
 		[-zip]=false
 
-		[.help]='file'
+		[.help]='FILE'
 		[.argc]=1
 	)
 
@@ -2078,7 +2201,7 @@ filetype.is() {
 	local -A _=(
 		[-zip]=false
 
-		[.help]='file'
+		[.help]='FILE'
 		[.argc]=1
 	)
 
@@ -2169,7 +2292,7 @@ zip.unpack() {
 		[-force]=false
 		[-clean]=false
 
-		[.help]='file'
+		[.help]='[-(force|clean)=BOOL] FILE'
 		[.argc]=1-
 	)
 
@@ -2315,13 +2438,13 @@ zip._prep_untar_() {
 	fi
 }
 
-declare -Ag help=(
+declare -Ag _help=(
+	['help']='Display help'
 	['say']='Print messages on standard error'
-	['cry']='Print warning messages on standard error'
 	['die']='Print error messages and exit failure'
+	['cry']='Print warning messages on standard error'
 	['bug']='Report bug and exit failure'
-	['bye']='Print messages and exit successfully'
-	['hey']='Print colored messages'
+	['hey']='Print messages taking attention'
 	['self version']='Print self version'
 	['self name']='Print self name'
 	['self path']='Print self path'
@@ -2354,37 +2477,13 @@ declare -Ag help=(
 	['unzip']='Unpack compressed file'
 )
 
-.usage() {
-	local cmd
-
-	say "Usage:    $0 commands ..."
-	say "Commands:"
-
-	# shellcheck disable=2154
-	for cmd in "${!help[@]}"; do
-		printf "\\t%-24s  %s\n" "$cmd" "${help[$cmd]}"
-	done | sort >&2
-}
-
-.help() {
-	if [[ $# -eq 0 ]]; then
-		.usage
-		die 'Help topic required.'
-	fi
-
-	local subject=${help["${*}"]:-}
-
-	[[ -n ${subject:-} ]] || die "E: No help found: ${*}."
-	bye "$subject"
-}
-
-declare -Ag command=(
-	['say']='say'
-	['cry']='cry'
-	['die']='die'
-	['bug']='bug'
-	['bye']='bye'
-	['hey']='hey'
+declare -Ag _command=(
+	['help']='help'
+	['say']='ui.say'
+	['die']='ui.die'
+	['cry']='ui.cry'
+	['bug']='ui.bug'
+	['hey']='ui.hey'
 	['self version']='self.version'
 	['self name']='self.name'
 	['self path']='self.path'
@@ -2417,41 +2516,66 @@ declare -Ag command=(
 	['unzip']='zip.unpack'
 )
 
-.dispatch() {
-	local -a args=("$@")
+.usage() {
+	local cmd
 
+	# shellcheck disable=2128
+	say "$PROGNAME COMMAND [SUBCOMMAND...] [-FLAG=VALUE...] [ARGS]"
+	say "Commands:"
+
+	# shellcheck disable=2154
+	for cmd in "${!_help[@]}"; do
+		printf "\\t%-24s  %s\n" "$cmd" "${_help[$cmd]}"
+	done | sort >&2
+}
+
+.execute() {
 	if [[ $# -eq 0 ]]; then
 		.usage
-		die 'Command required.'
+		die 'Command required'
 	fi
+
+	local help=
 
 	if [[ $1 = help ]]; then
+		help=true
+
 		shift
 
-		.help "$@"
-		exit
+		if [[ $# -eq 0 ]]; then
+			.usage
+			die 'Help topic required.'
+		fi
 	fi
 
-	local -a try
+	local -a args=("$@")
+
+	local fun
+	local try cmd
+
 	while [[ $# -gt 0 ]]; do
 		try+=("$1")
 		shift
 
-		local key="${try[*]}"
-
-		local func
-		func=${command["$key"]:-}
-
-		if [[ -n $func ]]; then
-			# shellcheck disable=2034
-			readonly COMMAND=$key
-
-			"$func" "$@"
-			return $?
+		if [[ -n ${_command["${try[*]}"]:-} ]]; then
+			cmd="${try[*]}"; fun=${_command[$cmd]}
+			break
 		fi
 	done
 
-	die "No command found: ${args[*]}."
+	if [[ -z ${fun:-} ]]; then
+		die "No command found: ${args[*]}"
+	fi
+
+	if [[ -n ${help:-} ]]; then
+		say "${_help[$cmd]}" ""
+
+		"$fun" -help
+	else
+		PROGNAME+=("$cmd"); readonly PROGNAME
+
+		"$fun" "$@"
+	fi
 }
 
 .source() {
@@ -2482,6 +2606,10 @@ declare -Ag command=(
 		"$UNDERSCORE" die "$@"; exit $?
 	}
 
+	_.cry() {
+		"$UNDERSCORE" cry "$@"; exit $?
+	}
+
 	_.bye() {
 		"$UNDERSCORE" bye "$@"; exit $?
 	}
@@ -2509,7 +2637,7 @@ _() {
 	local cmd=$1
 
 	case $cmd in
-	die|bye|bug|enter|leave) shift; _."$cmd" "$@" ;;
+	die|cry|bye|bug|enter|leave) shift; _."$cmd" "$@" ;;
 	*)                       "$UNDERSCORE" "$@"   ;;
 	esac
 }
@@ -2537,7 +2665,7 @@ main() {
 		.source "$@"
 	else
 		.init
-		.dispatch "$@"
+		.execute "$@"
 	fi
 }
 
diff --git a/src/she b/src/she
--- a/src/she
+++ b/src/she
@@ -6,11 +6,15 @@
 
 #:lib/_.sh
 
+#:lib/flag.sh
+
+#:lib/help.sh
+
+#:lib/ui.sh
+
 #:lib/must.sh
 
 #:lib/self.sh
-
-#:lib/flag.sh
 
 #:lib/string.sh
 
@@ -44,69 +48,70 @@
 
 #:lib/zip.sh
 
-#/help/
+#/_help/
+
+#/_command/
 
 .usage() {
 	local cmd
 
-	say "Usage:    $0 commands ..."
+	# shellcheck disable=2128
+	say "$PROGNAME COMMAND [SUBCOMMAND...] [-FLAG=VALUE...] [ARGS]"
 	say "Commands:"
 
 	# shellcheck disable=2154
-	for cmd in "${!help[@]}"; do
-		printf "\\t%-24s  %s\n" "$cmd" "${help[$cmd]}"
+	for cmd in "${!_help[@]}"; do
+		printf "\\t%-24s  %s\n" "$cmd" "${_help[$cmd]}"
 	done | sort >&2
 }
 
-.help() {
+.execute() {
 	if [[ $# -eq 0 ]]; then
 		.usage
-		die 'Help topic required.'
+		die 'Command required'
 	fi
 
-	local subject=${help["${*}"]:-}
-
-	[[ -n ${subject:-} ]] || die "E: No help found: ${*}."
-	bye "$subject"
-}
-
-#/command/
-
-.dispatch() {
-	local -a args=("$@")
-
-	if [[ $# -eq 0 ]]; then
-		.usage
-		die 'Command required.'
-	fi
+	local help=
 
 	if [[ $1 = help ]]; then
+		help=true
+
 		shift
 
-		.help "$@"
-		exit
+		if [[ $# -eq 0 ]]; then
+			.usage
+			die 'Help topic required.'
+		fi
 	fi
 
-	local -a try
+	local -a args=("$@")
+
+	local fun
+	local try cmd
+
 	while [[ $# -gt 0 ]]; do
 		try+=("$1")
 		shift
 
-		local key="${try[*]}"
-
-		local func
-		func=${command["$key"]:-}
-
-		if [[ -n $func ]]; then
-			# shellcheck disable=2034
-			readonly COMMAND=$key
-
-			"$func" "$@"
-			return $?
+		if [[ -n ${_command["${try[*]}"]:-} ]]; then
+			cmd="${try[*]}"; fun=${_command[$cmd]}
+			break
 		fi
 	done
 
-	die "No command found: ${args[*]}."
+	if [[ -z ${fun:-} ]]; then
+		die "No command found: ${args[*]}"
+	fi
+
+	if [[ -n ${help:-} ]]; then
+		say "${_help[$cmd]}" ""
+
+		"$fun" -help
+	else
+		PROGNAME+=("$cmd"); readonly PROGNAME
+
+		"$fun" "$@"
+	fi
 }
 
 .source() {
@@ -127,6 +132,10 @@
 
 	_.die() {
 		"$UNDERSCORE" die "$@"; exit $?
+	}
+
+	_.cry() {
+		"$UNDERSCORE" cry "$@"; exit $?
 	}
 
 	_.bye() {
@@ -156,7 +165,7 @@ _() {
 	local cmd=$1
 
 	case $cmd in
-	die|bye|bug|enter|leave) shift; _."$cmd" "$@" ;;
+	die|cry|bye|bug|enter|leave) shift; _."$cmd" "$@" ;;
 	*)                       "$UNDERSCORE" "$@"   ;;
 	esac
 }
@@ -184,7 +193,7 @@ main() {
 		.source "$@"
 	else
 		.init
-		.dispatch "$@"
+		.execute "$@"
 	fi
 }
 
