.

diff --git a/she b/she
--- a/she
+++ b/she
@@ -763,7 +763,7 @@ temp.clean() {
 
 # os.virtual: Which virtualization
 os.virtual() {
-	systemd-detect-virt
+	systemd-detect-virt || true
 }
 
 # os.distribution: Which distribution
@@ -1798,7 +1798,6 @@ filetype.mime() {
 	flag.parse "$@"
 
 	local file=${_[1]?${FUNCNAME[0]}: missing value}
-
 	must.f "$file"
 
 	if flag.true zip; then
@@ -1817,16 +1816,16 @@ filetype.is() {
 
 	flag.parse "$@"
 
-	local -a args; flag.args args
+	local file=${_[1]?${FUNCNAME[0]}: missing value}
+	must.f "$file"
 
+	local -a args; flag.args args
 	filetype.is_ "${args[@]}"
 }
 
 filetype.is_() {
 	local file=${1?${FUNCNAME[0]}: missing argument}; shift
 	local type=${1?${FUNCNAME[0]}: missing argument}; shift
-
-	must.f "$file"
 
 	local func=filetype.is._"${type}"_
 
@@ -1852,9 +1851,11 @@ filetype.is._mime_() {
 }
 
 filetype.is._program_() {
+	local file=${1?${FUNCNAME[0]}: missing argument}; shift
+
 	local mime encoding
 
-	IFS='; ' read -r mime encoding < <(file --mime --brief "$1")
+	IFS='; ' read -r mime encoding < <(file --mime --brief "$file")
 
 	if [[ $encoding =~ binary$ ]]; then
 		if [[ $mime  =~ -executable$ ]]; then
@@ -1872,13 +1873,15 @@ filetype.is._program_() {
 }
 
 filetype.is._compressed_() {
-	local mime; mime=$(file --mime-type --brief "$1")
+	local file=${1?${FUNCNAME[0]}: missing argument}; shift
+
+	local mime; mime=$(file --mime-type --brief "$file")
 
 	case $mime in
-	gzip|zip|x-xz|x-bzip2|x-zstd)
+	application/gzip|application/zip|application/x-xz|application/x-bzip2|application/x-zstd)
 		local zip=$mime; zip=${zip##*/}; zip=${zip##*-}
 
-		if [[ $(file --mime-type --brief --uncompress-noreport "$file") = tar ]]; then
+		if [[ $(file --mime-type --brief --uncompress-noreport "$file") = application/x-tar ]]; then
 			_[.file.zip]=tar.$zip
 		else
 			_[.file.zip]=$zip
@@ -1892,82 +1895,150 @@ filetype.is._compressed_() {
 
 # unzip: Unpack compressed file
 zip.unpack() {
-	local in=${1?${FUNCNAME[0]}: missing argument};  shift
-	local out=${1?${FUNCNAME[0]}: missing argument}; shift
+	local -A _=(
+		[-force]=false
+	)
+
+	flag.parse "$@"
+
+	local in=${_[1]:-} out=${_[2]:-}
+
+	[[ -n $in ]] || die "Missing input file: $in"
 
 	must.f "$in"
 
-	local -A _
+	filetype.is_ "$in" compressed || die "Not a compressed file of known type: $in"
 
-	file.is_ compressed "$in" || die "Not a compressed file of known type: $in"
+	local func=zip._unpack_.${_[.file.zip]:-}
 
-	local func=zip._unpack.${_[.file.zip]:-}
-
-	must.callable "$func" "Unsupported compressed file type: $zip"
+	must.callable "$func" "Unsupported compressed file: $in"
 
 	"$func" "$in" "$out"
 }
 
-zip._unpack.tar.gz() {
-	tar --strip-components=1 -zxvf "$1" -C "$2"
+zip._unpack_.tar.gz() {
+	local in=${_[1]?${FUNCNAME[0]}: missing value}; out=${_[2]:-}
+
+	zip._prep_untar_
+
+	tar --strip-components=1 -zxvf "$in" -C "$out"
 }
 
-zip._unpack.tar.bz2() {
-	must.available bzip2
+zip._unpack_.tar.bz2() {
+	local in=${_[1]?${FUNCNAME[0]}: missing value}; out=${_[2]:-}
 
-	tar --strip-components=1 -jxvf "$1" -C "$2"
+	zip._prep_untar_ bzip2
+
+	tar --strip-components=1 -jxvf "$in" -C "$out"
 }
 
-zip._unpack.tar.xz() {
-	must.available xz
+zip._unpack_.tar.xz() {
+	local in=${_[1]?${FUNCNAME[0]}: missing value}; out=${_[2]:-}
 
-	tar --strip-components=1 -Jxvf "$1" -C "$2"
+	zip._prep_untar_ xz
+
+	tar --strip-components=1 -Jxvf "$in" -C "$out"
 }
 
-zip._unpack.tar.zst() {
-	must.available zstd
+zip._unpack_.tar.zst() {
+	local in=${_[1]?${FUNCNAME[0]}: missing value}; out=${_[2]:-}
 
-	tar --strip-components=1 --zstd -xvf "$1" -C "$2"
+	zip._prep_untar_ zstd
+
+	tar --strip-components=1 --zstd -xvf "$in" -C "$out"
 }
 
-zip._unpack.zip() {
-	must.available unzip
+zip._unpack_.zip() {
+	local in=${_[1]?${FUNCNAME[0]}: missing value}; out=${_[2]:-}
 
-	unzip -q -d "$2" "$1"
+	zip._prep_unzip_ unzip
+
+	unzip -q -d "$out" "$in"
 }
 
-zip._unpack.gz() {
-	local tempfile
-	temp.file tempfile
+zip._unpack_.gz() {
+	local in=${_[1]?${FUNCNAME[0]}: missing value}; out=${_[2]:-}
 
-	zcat "$1" >"$tempfile" && mv "$tempfile" "$2"
-}
-
-zip._unpack.bz2() {
-	must.available bzcat
-
-	local tempfile
-	temp.file tempfile
-
-	bzcat "$1" >"$tempfile" && mv "$tempfile" "$2"
-}
-
-zip._unpack.xz() {
-	must.available unxz
-
-	local tempfile
-	temp.file tempfile
-
-	unxz "$1" >"$tempfile" && mv "$tempfile" "$2"
-}
-
-zip._unpack.zst() {
-	must.available zstdcat
+	zip._prep_unzip_ zcat
 
 	local tempfile
 	temp.file tempfile
 
-	zstdcat -f "$1" >"$tempfile" && mv "$tempfile" "$2"
+	zcat "$in" >"$tempfile" && mv "$tempfile" "$out"
+}
+
+zip._unpack_.bz2() {
+	local in=${_[1]?${FUNCNAME[0]}: missing value}; out=${_[2]:-}
+
+	zip._prep_unzip_ bzcat
+
+	local tempfile
+	temp.file tempfile
+
+	bzcat "$in" >"$tempfile" && mv "$tempfile" "$out"
+}
+
+zip._unpack_.xz() {
+	local in=${_[1]?${FUNCNAME[0]}: missing value}; out=${_[2]:-}
+
+	zip._prep_unzip_ unxz
+
+	local tempfile
+	temp.file tempfile
+
+	unxz "$in" >"$tempfile" && mv "$tempfile" "$out"
+}
+
+zip._unpack_.zst() {
+	local in=${_[1]?${FUNCNAME[0]}: missing value}; out=${_[2]:-}
+
+	zip._prep_unzip_ zstdcat
+
+	local tempfile
+	temp.file tempfile
+
+	zstdcat -f "$in" >"$tempfile" && mv "$tempfile" "$out"
+}
+
+zip._prep_unzip_() {
+	local in=${_[1]?${FUNCNAME[0]}: missing value}; out=${_[2]:-}
+
+	local prog
+	for prog; do
+		must.available "$prog"
+	done
+
+	[[ -n $out ]] || out=${in%.*}
+
+	if [[ -e $out ]]; then
+		if flag.true force; then
+			must.success rm -rf -- "$out"
+		else
+			die "File already exist: $out"
+		fi
+	fi
+}
+
+zip._prep_untar_() {
+	local in=${_[1]?${FUNCNAME[0]}: missing value}; out=${_[2]:-}
+
+	local prog
+	for prog; do
+		must.available "$prog"
+	done
+
+	[[ -n $out ]] || out=${in%.tar.*}
+
+	if [[ -e $out ]]; then
+		if flag.true force; then
+			must.success rm -rf -- "$out"
+		else
+			die "Directory already exist: $out"
+		fi
+		must.success mkdir -p "$out"
+	else
+		must.success mkdir -p "$out"
+	fi
 }
 
 declare -Ag help=(
