.

diff --git a/she b/she
--- a/she
+++ b/she
@@ -99,8 +99,23 @@ const() {
 ensured() {
 	local -n variable_=$1
 
-	[[ -n ${!variable_} ]] || die "Blank environment value found: $variable_"
-	must mkdir -p "${!variable_}"
+	[[ -n $variable_ ]] || die "Blank environment value found: $variable_"
+	[[ -d $variable_ ]] || must mkdir -p "$variable_"
+}
+
+# Check timestamp of reference files against given expiry
+expired() {
+	local expiry=$1
+	shift
+
+	local file
+	for file; do
+		if [[ -e $file ]] && [[ $(( $(date +%s) - $(stat -c %Y "$file") )) -le $expiry ]]; then
+			return 1
+		fi
+	done
+
+	return 0
 }
 
 # Ensure a public a variable name
@@ -117,8 +132,8 @@ narg() {
 	local lower=$1 upper=$2
 	shift 2
 
-	[[ $# -ge $lower                                 ]] || bug "Too few arguments: $*"
-	[[ -n $upper && $upper != - && $upper -le $upper ]] || bug "Too many arguments: $*"
+	[[ $lower = - || $# -ge $lower               ]] || bug "Too few arguments: $*"
+	[[ -z $upper  || $upper = - || $# -le $upper ]] || bug "Too many arguments: $*"
 }
 
 # Initialize underscore system
@@ -341,7 +356,8 @@ temp.inside() {
 
 	if [[ -n $outdir  ]]; then
 		[[ -z $parents ]] || must mkdir -p "$outdir"
-		cp -aT "$tempdir" "$outdir"
+		must cp -aT "$tempdir" "$outdir"
+		must chmod 755 "$outdir"
 	fi
 
 	rm -rf -- "$tempdir"
@@ -357,7 +373,7 @@ array.join() {
 	echo "$*"
 }
 
-# Parse URL
+# URL processing
 
 url.parse() {
 	local prefix_=.
@@ -472,27 +488,14 @@ url.is_git() {
 
 	[[ -n ${remote_[git]:-} ]]
 }
-#
-# url.test() {
-# 	# shellcheck disable=2034
-# 	local -A there here
-#
-# 	url.parse -prefix /usr/local/src "$@" there here
-#
-# 	debug.dump there
-# 	debug.dump here
-#
-# 	if url.is_git there; then
-# 		echo OK
-# 	else
-# 		echo NOTOK
-# 	fi
-# }
-#
-# url.test "$@"
-# exit
 
 # Git functions
+
+declare -Ag _git=(
+	[lazy_expiry]=3600
+	[eager_expiry]=180
+	[shibboleth]=_
+)
 
 git.must_sane() {
 	git rev-parse --is-inside-work-tree &>/dev/null || die "Must be inside a git work tree: $PWD"
@@ -522,9 +525,64 @@ git.top() {
 	must cd "$(git.topdir)"
 }
 
+# shellcheck disable=2120
+git.refresh() {
+	local branch=master expiry=180
+
+	while [[ $# -gt 0 ]]; do
+		case $1 in
+		-expiry|--expiry)
+			[[ $# -gt 1 ]] || die "Argument required for flag: $1"
+			shift
+
+			expiry=$1
+			shift
+			;;
+		-branch|--branch)
+			[[ $# -gt 1 ]] || die "Argument required for flag: $1"
+			shift
+
+			branch=$1
+			shift
+			;;
+		-*)
+			die "Unrecognized flag: $1"
+			;;
+		*)
+			break
+			;;
+		esac
+	done
+
+	narg 0 0 "$@"
+
+	if expired "$expiry" .git/"${_git[shibboleth]}" .git/FETCH_HEAD; then
+		git.must_clean
+		git checkout --quiet "$branch"
+		git pull --quiet origin "$branch"
+
+		must touch .git/"${_git[shibboleth]}"
+	fi
+}
+
+# shellcheck disable=2120
+git.always_refresh() {
+	git.refresh -branch "${1:-master}" -expiry 0
+}
+
+# shellcheck disable=2120
+git.lazy_refresh() {
+	git.refresh -branch "${1:-master}" -expiry "${_git[lazy_expiry]}"
+}
+
+# shellcheck disable=2120
+git.eager_refresh() {
+	git.refresh -branch "${1:-master}" -expiry "${_git[eager_expiry]}"
+}
+
 # git.get: Get (clone or update) Git repository
 git.get() {
-	local prefix=${_SRC_DIR:-} branch='' shallow=''
+	local prefix=${_SRC_DIR:-} branch='' shallow='' cached=''
 
 	while [[ $# -gt 0 ]]; do
 		case $1 in
@@ -545,6 +603,11 @@ git.get() {
 			;;
 		-shallow|--shallow)
 			shallow=true
+			shift
+			;;
+		-cached|--cached)
+			cached=true
+			shift
 			;;
 		-*)
 			die "Unrecognized flag: $1"
@@ -577,12 +640,17 @@ git.get() {
 		temp.inside "${flags[@]}" "${args[@]}"
 
 		must cd "$repo"
+		must touch .git/"${_git[shibboleth]}"
 	else
 		must cd "$repo"
 
-		git.must_clean
-		git checkout "${branch:-master}"
-		git pull origin "${branch:-master}"
+		if [[ -n ${cached:-} ]]; then
+			# shellcheck disable=2119
+			git.lazy_refresh
+		else
+			# shellcheck disable=2119
+			git.eager_refresh
+		fi
 	fi
 }
 
@@ -830,13 +898,13 @@ declare -Ag command=(
 	cat <<'EOF'
 .() {
 	# Standard prelude
-	
+
 	[ -n "${BASH_VERSION:-}"        ] || { echo >&2 'Bash required.';                         exit 1; }
 	[[ ${BASH_VERSINFO[0]:-} -ge 4 ]] || { echo >&2 'Bash version 4 or higher required.';     exit 1; }
 	[[ -x /usr/bin/apt-get         ]] || { echo >&2 'Only Debian and derivatives supported.'; exit 1; }
-	
+
 	set -Eeuo pipefail; shopt -s nullglob; [[ -z ${TRACE:-} ]] || set -x; unset CDPATH
-	
+
 	export LC_ALL=C.UTF-8 LANG=C.UTF-8
 
 	declare -grx UNDERSCORE=$UNDERSCORE
